<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="applicable-device" content="mobile">
    <title>宠爱之家-宠物理发</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/css/mobile/sm.min.css">
    <link rel="stylesheet" href="/css/mobile/reset.css">
    <link rel="stylesheet" href="/css/mobile/pethaircut.css">
</head>
<body>
<div class="page">
    <div class="content">
        <!-- detail -->
        <div class="bdy">
            <h1 class="ribbonmobile" style="color: #333;font-weight: 600;">千万不要随便带宠物去理发！理发师来谈谈.....</h1>
            <p>不知道你有没有过这样的想法</p>
            <p>看到别人家的狗狗</p>
            <p>送进美容院经过Tony老师的一番收拾</p>
            <p>发生了翻天覆地的变化</p>
            <p>比如</p>
            <p>稍微打理一下毛发</p>
            <p>秒变一只可爱的糯米团子</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l1.jpg" alt="">
        </div>
        <div class="text">
            <p>前一秒</p>
            <p>还是放荡不羁爱自由的大叔</p>
            <p>后一秒</p>
            <p>就变成了拥有小鹿斑比眼睛的小鲜肉</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l2.jpg" alt="">
        </div>
        <div class="text">
            <p>Tony老师剪刀动一动</p>
            <p>就能化腐朽为神奇</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l3.jpg" alt="">
        </div>
        <div class="text">
            <p>于是想着把自家狗狗也送进去</p>
            <p>说不定出来以后</p>
            <p>美丽帅气的连自己都不认识了</p>
            <p>但！是！各！位！</p>
            <p>理想很丰满，现实很骨感</p>
            <p>毕竟不是每一只狗狗</p>
            <p>在tony老师的倒腾下</p>
            <p>都能变成你理想中的样子</p>
            <p>还有很多狗狗</p>
            <p>从美容院出来之后</p>
            <p>整个狗生都改变了</p>
            <p>妈妈让Tony老师帮我剪一下毛</p>
            <p>还特意嘱咐把我的毛留长点</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l4.jpg" alt="">
        </div>
        <div class="text">
            <p>但...这嘛玩意？草泥马吗😳</p>
            <p>Tony老师你是不是对“长点”有什么误解！</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l5.jpg" alt="">
            <img src="/img/mobile/l6.jpg" alt="">
        </div>
        <div class="text">
            <p>憋说了，这回剪得连亲妈都不认识了</p>
            <p>但美容前</p>
            <p>虽然毛炸了一点</p>
            <p>但也是一只可爱的狗子</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l8.jpg" alt="">
        </div>
        <div class="text">
            <p>美容后</p>
            <p>粽子是你吗？粽子！</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l9.jpg" alt="">
        </div>
        <div class="text">
            <p>美容前</p>
            <p>是一个五官非常有特点的蓝孩子</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l10.jpg" alt="">
        </div>
        <div class="text">
            <p>美容后</p>
            <p>“我的耳朵去辣里了</p>
            <p>我有点方😳😳😳”</p>
        </div>
        <div class="pic">
            <img src="/img/mobile/l11.jpg" alt="">
        </div>
        <div class="text">
            <p>所以说</p>
            <p>碰到一个靠谱的造型师多么重要啊</p>
            <p>否则你永远猜不到在他的“神剪”下</p>
            <p>自家宠物会变成什么样</p>
            <p>哈哈哈哈哈哈哈哈哈哈哈哈</p>
        </div>
        <div class="unauthorized">
            <p>以上内容均为宠爱之家原创稿件，未经授权，谢绝转载，如需转载请联系本站并保留以上全部内容。更多精彩，尽在宠爱之家！注：文章所有图片均来自于网络</p>
        </div>
        <!--footer-->
        <div class="footer">
            Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved
            <a href="http://www.miitbeian.gov.cn" external rel="nofollow">粤ICP备18083935号</a>
        </div>
    </div>
</div>

<script type='text/javascript' src='/js/mobile/test.js' charset='utf-8'></script>
<script type='text/javascript' src='/js/mobile/sm.min.js' charset='utf-8'></script>
</body>
</html>
