<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="applicable-device" content="mobile">
    <title>宠爱之家-使用规范</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/css/mobile/sm.min.css">
    <link rel="stylesheet" href="/css/mobile/reset.css">
    <link rel="stylesheet" href="/css/mobile/petusing.css">
</head>
<body>
<div class="page">
    <div class="content">
        <!-- detail -->
        <div class="text">
            <p style="color: #333;font-weight: 600;">封号</p>
            <p>以下情况可能会导致帐号被封禁。</p>
            <p>盗图</p>
            <p>盗图，包括在「宠爱之家」内发布盗版的图像、将「宠爱之家」内的作品未经作者授权地泄漏到其他地方。</p>
            <p>说盗图大家都知道，我们来说说什么样的非原创内容可以在「宠爱之家」里发：</p>
            <p>不能收费，若收费则意味着发布者获得了版权方的商业授权，而这几乎不可能。只要看到了收费的非原创内容立刻封号。非商业的情况，需要原作者拥有作品的「发表权」，即作品允许被转载。若原作者保留了「署名权」则必须署名原作者是谁。</p>
            <p>组织卖淫</p>
            <p>对于所谓的「线下」，「宠爱之家」态度十分明确，那就是禁止。任何在「宠爱之家」内发布卖淫信息的作者将受到最低 7 天、最高永久的封号处理。</p>
            <p>多次发布违规内容</p>
            <p>在对社区审查规则知情的情况下，恶意发布违规内容，扰乱社区秩序的作者将受到最低 7 天、最高永久的封号处理。</p>

            <p style="color: #333;font-weight: 600;">和谐的尺度</p>
            <p>根据「互联网禁止传播淫秽、色情等不良信息自律规范」（以后简称规范），以下内容会被和谐：</p>
            <p>淫亵性地具体描写性行为、性交及其心理感受</p>
            <p>淫亵性地描述或者传授性技巧</p>
            <p>具体描写乱伦、强奸及其他性犯罪的手段、过程或者细节，可能诱发犯罪的</p>
            <p>具体描写少年儿童的性行为</p>
            <p>淫亵性地具体描写同性恋的性行为或者其他性变态行为，以及具体描写与性变态有关的暴力、虐待、侮辱行为</p>
            <p>其他令普通人不能容忍的对性行为淫亵性描写</p>
            <p>我们认为这套标准的许多条例十分主观。中东人与荷兰人对待色情的标准不一样，中国人与中国人之间对待色情的标准也不一样。因此，我们根据「规范」制定了以下「宠爱之家」运营中真正执行的标准，「宠爱之家」的运营同事按照此标准进行尺度审查，也欢迎大家提意见，共同完善一套较为客观的审查标准：</p>
            <p>露点以及半透明的遮挡</p>
            <p>露晕、露毛以及半透明的遮挡</p>
            <p>跳蛋、按摩棒，乳夹等性爱玩具与人体接触的画面</p>
            <p>对性行为的描述，比如两人摆出交媾的姿势（包括但不限于口交、后入等）、小视频里的叫床声、任何形式的自慰画面</p>
            <p>过于低俗的内容，比如放尿与姨妈</p>
            <p>主要内容为刻意展现隐私部位</p>
            <p>违背他人意愿，侵犯他人肖像权的内容，比如「能分辨出是谁的」偷拍</p>
            <p>原创作品中的非原创内容（比如用各大社交平台上的用户照片，作为自己的头像。）</p>
            <p>被和谐后的内容即使购买、购买后收藏，也是不能看的。</p>
        </div>
    </div>
</div>

<script type='text/javascript' src='/js/mobile/test.js' charset='utf-8'></script>
<script type='text/javascript' src='/js/mobile/sm.min.js' charset='utf-8'></script>
</body>
</html>
