<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多肉盒子APP后台管理-游戏礼包</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css?v=20193201138" rel="stylesheet" />
    <link href="/public/css/gamegift/gamegift.css?v=20194241429" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto" style="margin-left: 10px;">
    <form action="/admin/newssearch" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <button type="button" class="layui-btn layui-btn-normal">
                    <a href="addgamegift" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增礼包</span></a>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>礼包名称</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>游戏名称</span></div></th>
                    <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>创建时间</span></div></th>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>礼包过期时间</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>礼包过期状态</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>礼包状态</span></div></th>
                    <th class="laytable-cell-1-0-7"><div class="layui-table-cell"><span>剩余数量</span></div></th>
                    <th class="laytable-cell-1-0-8 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($gift as $k=>$v): ?>
                    <tr>
                        <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['id']?></span></div></td>
                        <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['giftbag_name']?></span></div></td>
                        <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['game_name']?></span></div></td>
                        <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$v['create_time'])?></span></div></td>
                        <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>
                                    <?php
                                   if(empty($v['end_time']))
                                   {
                                       echo date("Y-m-d H:i:s",$v['end_date']);
                                   }
                                   else{
                                       echo date("Y-m-d H:i:s",$v['end_time']);
                                   }
                                    ?>
                                </span></div></td>
                        <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>
                                    <?php
                                    if(empty($v['end_time']))
                                    {
                                       if($v['end_date']<time())
                                       {
                                           echo "已过期";
                                       }
                                       else{
                                           echo "未过期";
                                       }
                                    }
                                    else{
                                        if($v['end_time']<time())
                                        {
                                            echo "已过期";
                                        }
                                        else{
                                            echo "未过期";
                                        }
                                    }
                                    ?>
                                </span></div></td>
                        <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span> <?php
                                    if($v['status']==1)
                                    {
                                        echo "开启";
                                    }
                                    else{
                                        echo "关闭";
                                    }
                                    ?></span></div></td>

                        <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=$v['remain_count']?></span></div></td>
                        <td class="laytable-cell-1-0-8"><div class="layui-table-cell">
                                <span class="layui-btn layui-btn-xs layui-btn-success" onclick="window.location.href='/gamegift/editgamegift?id=<?=$v['id']?>'">
                                    编辑</span>
                                <span class="layui-btn layui-btn-xs layui-btn-danger" onclick="window.location.href='/gamegift/delgift?id=<?=$v['id']?>'">
                                    删除</span></div>
                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
