<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-地图帖子列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/map/list.css?=201812128" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题文档</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入标题文档" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>地图类型</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>对象</span></div></th>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>标题</span></div></td>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>精准地点</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>内容</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>联系方式</span></div></th>
                    <th class="laytable-cell-1-0-7"><div class="layui-table-cell"><span>发布时间</span></div></th>
                    <th class="laytable-cell-1-0-8"><div class="layui-table-cell"><span>剩余时间</span></div></th>
                    <th class="laytable-cell-1-0-9 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach($page as $k=>$v): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=get_zs_map_type_name($v['map_id'])?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['object']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$v['title']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$v['lbs']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=$v['content']?></span></div></td>
                    <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=$v['tel']?></span></div></td>
                    <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$v['create_time'])?></span></div></td>
                    <td class="laytable-cell-1-0-8"><div class="layui-table-cell"><span><?=$v['end_time']?>小时</span></div></td>
                    <td class="laytable-cell-1-0-9"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$v['id']?>" onclick="del(this)">删除</span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    let del = (tag)=>{
        let id = $(tag).data('id');
        $.get("/map/del",{id:id},(msg)=>{
            if(msg.msg == 'ok'){
                window.location.href = "/map/list";
            }else{
                layer.msg('删除失败', {icon: 5});
            }
        },"json");
    }
</script>
</body>
</html>
