<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-地图分类</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/map/type.css?v=2018122117" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">分类名称</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入分类名称" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
            <div class="layui-inline">
                <button type="button" class="layui-btn layui-btn-normal">
                    <a href="addtype" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增分类</span></a>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>标题</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>描述</span></div></th>
                    <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>色值</span></div></th>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>分类图片(110px * 110px)</span></div></th>
                    <th class="laytable-cell-1-0-5 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($data as $v): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['map_id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['title']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['info']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><input type="color" value="#<?=$v['color']?>" readonly="readonly" ></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><img class="layui-table-img" src="<?=$v['img']?>" alt=""></div></td>
                    <td class="laytable-cell-1-0-5">
                        <div class="layui-table-cell">
                            <span class="layui-btn layui-btn-xs layui-btn-info" data-id="<?=$v['map_id']?>" onclick="edit(this)">编辑</span>
                            <span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$v['map_id']?>" onclick="del(this)">删除</span>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    let del = (tag)=>{
        let id = $(tag).data('id');
        $.get("/map/deltype",{id:id},(msg)=>{
            if(msg.msg == 'ok'){
                window.location.href = "/map/type";
            }else{
                layer.msg('删除失败', {icon: 5});
            }
        },"json");
    };
    let edit = (tag)=>{
        let id = $(tag).data('id');
        window.location.href = "/map/edittype?id="+id;
    };
</script>
</body>
</html>
