<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-宠服banner</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/shop/banner.css?v=2018122129" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>banner名称</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>图片</span></div></th>
                    <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>图片高宽</span></div></th>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>跳转地址</span></div></th>
                    <th class="laytable-cell-1-0-5 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($data as $k=>$v): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['name']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><img class="layui-table-img" src="<?=$v['pic']?>" alt=""></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$v['size']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$v['addr']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-" data-id="<?=$v['id']?>" onclick="edit(this)">编辑</span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    let edit = (tag)=>{
        let id = $(tag).data('id');
        window.location.href = "/shop/editbanner?id="+id;
    };
</script>
</body>
</html>
