<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="/public/js/jquery.js"></script>
</head>
<body>
    <div id="div_root" style="overflow: hidden; width: 80%; margin: 0 auto;">
        <div id="div_left" style="float: left; width: 30%;">
            <table border="1" cellspacing="0" cellpadding="5">
                <tr>
                    <td>ID</td>
                    <td>订单号</td>
                </tr>
                <?php foreach ($data as $k=>$v): ?>
                    <tr>
                        <td><?=$v['id']?></td>
                        <td onclick="chk(this)"><?=$v['trade_no']?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div id="div_right" style="float: right; width: 70%;">
            <p>点击订单号自动生成订单详情</p>
        </div>
    </div>
    <script>
    function chk(tag) {
        var trade = tag.innerText;
        $.post("/pay/list",{trade_no:trade},function (msg) {
            console.log(msg);
            var htmltable = "<p>订单详情：</p> " +
                                "<table border='1' cellspacing='0' cellpadding='5'>" +
                                "<tr><td>app_id</td><td>"+msg.data.app_id+"</td></tr>" +
                                "<tr><td>nonce_str</td><td>"+msg.data.nonce_str+"</td></tr>" +
                                "<tr><td>biz_code</td><td>"+msg.data.biz_code+"</td></tr>" +
                                "<tr><td>biz_msg</td><td>"+msg.data.biz_msg+"</td></tr>" +
                                "<tr><td>attach</td><td>"+msg.data.biz_data.attach+"</td></tr>" +
                                "<tr><td>transaction_id</td><td>"+msg.data.biz_data.transaction_id+"</td></tr>" +
                                "<tr><td>out_trade_no</td><td>"+msg.data.biz_data.out_trade_no+"</td></tr>" +
                                "<tr><td>fee_type</td><td>"+msg.data.biz_data.fee_type+"</td></tr>" +
                                "<tr><td>total_fee</td><td>"+msg.data.biz_data.total_fee+"</td></tr>" +
                                "<tr><td>trade_type</td><td>"+msg.data.biz_data.trade_type+"</td></tr>" +
                                "<tr><td>time_end</td><td>"+msg.data.biz_data.time_end+"</td></tr>" +
                                "<tr><td>trade_state</td><td>"+msg.data.biz_data.trade_state+"</td></tr>" +
                                "<tr><td>trade_state_desc</td><td>"+msg.data.biz_data.trade_state_desc+"</td></tr>" +
                            "</table>";
            $("#div_right").empty();
            $("#div_right").html(htmltable)
        },'json');
    }
    </script>
</body>
</html>
