<!doctype html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>游戏盒子APP后台管理-添加编辑签到</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addcheckin.css?v201932514" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="/index/addcheckin" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">非会员赠送</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">日期</label>
            <div class="layui-input-inline">
                <input type="text" class="giftnum" name="create_time" readonly value="<?=$data?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">签到icon</label>
            <div class="layui-input-inline">
                <input type="file" name="icon" value=""  class="signimgurl">
                <?php if($checkin['icon']){?>
                <img src="<?=$checkin['icon']?>" width="50" height="50" />
                <?php }?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">福利类型</label>
            <div class="layui-input-inline lay-input">
                <input type="radio" name="type"  value="积分" <?php if($checkin['type']=='积分'){echo "checked";}?>>积分
                <input type="radio" name="type"  value="优惠券" <?php if($checkin['type']=='优惠券'){echo "checked";}?>>优惠券
                <input type="radio" name="type"  value="礼包" <?php if($checkin['type']=='礼包'){echo "checked";}?>>礼包
            </div>
        </div>

        <!-- 自动生成end -->
        <div class="layui-form-item" id="game" <?php if($checkin['id'] && $checkin['type']=='礼包') echo 'style="display: block;"';else echo 'style="display: none;"';?>>
            <label class="layui-form-label">游戏名称</label>
            <div class="layui-input-inline">
                <select name="game_id" lay-verify="required" lay-search="" lay-filter="game">
                    <option value="0">直接选择或搜索选择</option>
                    <?php foreach ($game as $k=>$v): ?>
                        <option value="<?=$v['id']?>" <?php if($v['id']==$checkin['game_id'] ) echo "selected";?>><?=$v['game_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item" id="giftbox" <?php if($checkin['id'] && $checkin['type']=='礼包') echo 'style="display: block;"';else echo 'style="display: none;"';?>>
            <label class="layui-form-label">签到福利</label>
            <div class="layui-input-inline" id="gift">
                <select name="gift_id" >
                    <option value="0">请选择礼包</option>
                    <?php foreach ($gift as $k=>$v): ?>
                        <option value="<?=$v['id']?>" <?php if($v['id']==$checkin['gift_id']) echo "selected";?>><?=$v['giftbag_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <!-- 自动生成start -->
        <div class="layui-form-item" id="content_text">
            <?php if($checkin['type']=="积分"){?>
                <label class="layui-form-label">签到福利</label>
                <div class="layui-input-inline lay-input"><input type="number" placeholder="此处填写签到积分" class="giftnum" name="text" min="0" value="<?=$checkin['text']?>"></div>
            <?php }?>
            <?php if($checkin['type']=="优惠券"){?>
                <div class="layui-form-item">
                    <label class="layui-form-label">优惠券</label>
                    <?php foreach ($arr as $k=>$v):?>
                        <div class='layui-input-inline lay-inputimg' style="width: 100px;">
                            <div class='coupon' onclick='chk(this,this.dataset.iconid)' data-iconid="<?=$v['id']?>">
                                <img src='/public/img/index/6yuan_beijing.png' width='100' height='50'  />
                                <?php if($v['id'] == $checkin['text']): ?>
                                    <span style="display: inline-block; width: 100px; height: 50px; background: url(&quot;/public/img/index/selcet_djq.png&quot;) 0% 0% / 100px 50px; position: absolute; z-index: 99; top: 0px; left: 0px;"></span>
                                <?php else: ?>
                                    <span style='display: none; width: 100px; height: 50px;background: url(/public/img/index/selcet_djq.png);'></span>
                                <?php endif; ?>
                                <p style="position: absolute; top: 26%; left: 12%; color: white; font-weight: bold;">￥<?=$v['amount']?> 代金卷</p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class='layui-input-inline lay-inputimg' style="width: 100px;">
                        <div class='coupon' onclick='chk(this,this.dataset.iconid)' data-iconid="0">
                            <img src='/public/img/index/6yuan_beijing.png' width='100' height='50'  />
                            <span style='display: none; width: 100px; height: 50px;background: url(/public/img/index/selcet_djq.png);'></span>
                            <p style="position: absolute; top: 26%; left: 12%; color: white; font-weight: bold;">不选</p>
                        </div>
                    </div>
                    <input type='hidden' id='coupon_id' name='coupon_id' value='0'>
                </div>
            <?php }?>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="hidden" name="m" value="<?=$m?>" />
                <input type="submit" class="layui-btn" value="立即提交" />
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    layui.use(['form', 'layedit', 'laydate'], function(){
        var form = layui.form;
        form.on('radio',function(data){
            //alert(data.value);//判断单选框的选中值/
            if(data.value == '积分'){
                $("#content_text").empty();
                $("#game").hide();
                $("#giftbox").hide();
                $("#content_text").html("" +
                    "<label class='layui-form-label'>签到福利</label>"+
                    "<div class='layui-input-inline lay-input'>"+
                    "<input type='number' placeholder='此处填写签到积分' class='giftnum' name='text' min='0' value=''>"+
                    "</div>"
                );
              //  $("#content_info").html("<input type='text' placeholder='今日赠送20积分' class='giftnum' required name='info' value=''>");
            }else if(data.value == '优惠券'){
                $("#content_text").empty();
                $("#game").hide();
                $("#giftbox").hide();
                var strhtml = "";
                    strhtml +="<label class='layui-form-label'>签到福利</label>";
                    strhtml +="<div class='layui-input-inline lay-inputimg'>";
                    <?php foreach ($arr as $key=>$value): ?>
                    strhtml +="<div class='coupon' onclick='chk(this,this.dataset.iconid)' data-iconid='<?=$value['id']?>'>";
                    strhtml +="<img src='/public/img/index/6yuan_beijing.png' width='100' height='50'  />";
                    strhtml +="<span style='display: none; width: 100px; height: 50px;background: url(/public/img/index/selcet_djq.png);'></span>";
                    strhtml +="<p style='position: absolute; top: 26%; left: 12%; color: white; font-weight: bold;'>￥<?=$value['amount']?> 代金卷</p>";
                    strhtml +="</div>&nbsp;&nbsp;";
                    <?php endforeach; ?>
                    strhtml +="<input type='hidden' id='coupon' name='text' value=''>";
                    strhtml +="</div>";
                $("#content_text").html(strhtml);
              //  $("#content_info").html("<input type='text' placeholder='今日优惠券描述' class='giftnum' required name='info' value=''>");
            }else {
                $("#content_text").empty();
                $("#game").show();
                $("#giftbox").show();
            }
        });
        form.on('select(game)', function(tag){
            var httpurl = "http://127.0.0.1:20085";
            $.get("/index/getgiftbag",{game_id:tag.value},function(msg){
                var data=$.parseJSON(msg);
                var options='<select style=" display: block;padding-right: 30px;cursor: pointer;height: 38px;line-height: 1.3;line-height: 38px;border-width: 1px;' +
                    'border-style: solid;background-color: #fff;border-radius: 2px;width: 100%; " name="gift_id">';
                for(var i=0;i<data.length;i++)
                {
                    options=options+"<option value='"+data[i].id+"'>"+data[i].giftbag_name+"</option>";
                }
                options=options+"</select>";
                console.log(options)
                $("#gift").html(options);
            })
        });
    });

    function chk(that,data) {
        $(".coupon span").css("display","none");
        $(that).find("span").css({"display":"inline-block","position":"absolute","z-index":"99","top":"0","left":"0","backgroundSize":"100px 50px"});
        $("#coupon").val(data);
    }

</script>
</body>
</html>
