<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>游戏盒子APP后台管理-新闻添加</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addnews.css?v=2010" rel="stylesheet" />
    <style>

        #todo_c {display: none;height: 150px;overflow: auto;position: fixed;z-index: 9999;background: rgb(255, 255, 255);width: 188px;border: 1px solid rgb(230, 230, 230);margin-top: 2px;}
        #todo_c .todo-ltem:hover{background: #5FB878;color: #fff;}
    </style>
</head>
<body>
<form class="layui-form" action="/index/addnews" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">新闻添加</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">标题</label>
            <div class="layui-input-inline">
                <input type="text" name="title" placeholder="请输入标题" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">作者</label>
            <div class="layui-input-inline">
                <input type="text" name="author" placeholder="请输入作者" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">新闻分类</label>
            <div class="layui-input-inline">
                <select name="type">
                    <?php foreachoption($newstype,"obj"); ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">推荐位</label>
            <div class="layui-input-inline" style="width: 500px;margin-bottom: 20px;">
                <input type="checkbox" name="position[]" lay-skin="primary" title="首页推荐" value="1">
                <input type="checkbox" name="position[]" lay-skin="primary" title="列表推荐" value="2">
                <input type="checkbox" name="position[]" lay-skin="primary" title="频道推荐" value="3">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">游戏名称</label>
            <div class="layui-input-inline">
                <select name="game_id"  lay-search="" lay-filter="game">
                    <option value="0">直接选择或搜索选择</option>
                    <?php foreach ($gametype as $k=>$v): ?>
                        <option value="<?=$v['id']?>"><?=$v['game_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">点赞数</label>
            <div class="layui-input-inline">
                <input type="number" name="click" placeholder="请输入点赞数" autocomplete="off" class="layui-input" value="0">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">展示资源</label>
            <div class="layui-tab layui-tab-card layui_tab_img">
                <ul class="layui-tab-title" style="padding: 0;">
                    <li class="layui-this" onclick="show(1)">首页N格</li>
                    <li onclick="show(2)">首页单格</li>
                    <li onclick="show(3)">首页视频</li>
                </ul>
                <div class="layui-tab-content layui_content">
                    <div class="layui-tab-item layui-show" id="item1">
                        <input class="avatarinput" type="file" name="filename[]" value="">
                        <input class="avatarinput" type="file" name="filename[]" value="">
                        <input class="avatarinput" type="file" name="filename[]" value="">
                    </div>
                    <div class="layui-tab-item" id="item2">
                        <div class="layui_item_il">
                            <input class="avatarinput" type="file" name="filename[]" value="" disabled>
                        </div>
                    </div>
                    <div class="layui-tab-item" id="item3">
                        <div class="layui_item_il">
                            <input class="avatarinput" type="file" name="filename[]" value="" disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-form-item layui-form-text" id="textarea">
            <label class="layui-form-label">文章内容</label>
            <div class="layui-input-block">
                <textarea name="content" id="editor" style="display: none;"></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>



<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    layui.use('layedit', function(){
        var layedit = layui.layedit;
        layedit.set({
            uploadImage: {
                url: '/index/upload' //接口url
                ,type: 'post' //默认post
            },
            uploadVideo: {
                url: '/index/upload',
                accept: 'video',
                acceptMime: 'video/*',
                exts: 'mp4|flv|avi|rm|rmvb'
            },
        });
        layedit.build('editor');
        /*layedit.build('editor',{
            tool: ['strong','italic','underline','del','left','center','right','link','unlink','face','image','code','video'],
            uploadImage: {url: '/admin/upload', type: 'post'}
        });*/
    });

    //video
    /*var xhrOnProgress=function(fun) {
        console.log("xhrOnProgress")
        xhrOnProgress.onprogress = fun; //绑定监听
        //使用闭包实现监听绑
        return function() {
            //通过$.ajaxSettings.xhr();获得XMLHttpRequest对象
            var xhr = $.ajaxSettings.xhr();
            //判断监听函数是否为函数
            if (typeof xhrOnProgress.onprogress !== 'function')
                return xhr;
            //如果有监听函数并且xhr对象支持绑定时就把监听函数绑定上去
            if (xhrOnProgress.onprogress && xhr.upload) {
                xhr.upload.onprogress = xhrOnProgress.onprogress;
            }
            return xhr;
        }
    };*/


    function show(tag) {
        switch (tag){
            case 1:
                $("#textarea").css('display','block');
                $("#item1 input").removeAttr("disabled");
                $("#item2 input").attr("disabled","disabled");
                $("#item3 input").attr("disabled","disabled");
                break;
            case 2:
                $("#textarea").css('display','block');
                $("#item2 input").removeAttr("disabled");
                $("#item1 input").attr("disabled","disabled");
                $("#item3 input").attr("disabled","disabled");
                break;
            case 3:
                $("#textarea").css('display','none');
                $("#item3 input").removeAttr("disabled");
                $("#item1 input").attr("disabled","disabled");
                $("#item2 input").attr("disabled","disabled");
                break;
        }
    }
</script>
</body>
</html>
