<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多肉盒子APP后台管理-反馈意见</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/newstype.css?v=2018122117" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="/index/log" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">分类名称</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入分类名称" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th data-field="debug" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>debug</span></div></th>
                    <th data-field="info" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>info</span></div></th>
                    <th data-field="create_time" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>time</span></div></th>
                    <th data-field="tools" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>tools</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($newData as $key=>$value): ?>
                    <tr>
                        <td data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                        <td data-field="debug" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value['debug']?></span></div></td>
                        <td data-field="info" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value['info']?></span></div></td>
                        <td data-field="create_time" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$value['create_time'])?></span></div></td>
                        <td data-field="tools" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>修复</span></div></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
