<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-应用升级</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addsysnotice.css" rel="stylesheet" />
</head>
<body>
    <form class="layui-form" action="/index/editsetting" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id" value="<?=$arrData['id']?>">
        <div class="layui-card-header">APP更新添加</div>
        <div class="layui_body">
            <div class="layui-form-item">
                <label class="layui-form-label">APP版本号</label>
                <div class="layui-input-inline">
                    <input type="text" name="version_number" placeholder="请输入APP版本号" autocomplete="off" class="layui-input" value="<?=$arrData['version_number']?>">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">APP版本名字</label>
                <div class="layui-input-inline">
                    <input type="text" name="version_name" placeholder="请输入APP版本名字" autocomplete="off" class="layui-input" value="<?=$arrData['version_name']?>">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">是否强制更新</label>
                <div class="layui-input-inline" style=" width: 242px;height: 40px;line-height: 40px;">
                    <input type="radio" name="is_forced_update"  class="layui-input" value="1" <?php if($arrData['is_forced_update'] == '1'){ echo "checked";} ?> >强制更新
                    <input type="radio" name="is_forced_update"  class="layui-input" value="0" <?php if($arrData['is_forced_update'] == '0'){ echo "checked";} ?>>不强制更新
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">APP更新内容</label>
                <div class="layui-input-inline">
                    <textarea name="update_content" id="" placeholder="请输入APP版本号" rows="5" cols="35"><?=$arrData['update_content']?></textarea>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">更新地址</label>
                <div class="layui-input-inline">
                    <input type="file" accept="application/vnd.android.package-archive" name="update_address" class="layui-input layui-pic">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">选择渠道</label>
                <div class="layui-input-inline">
                    <select name="type">
                        <option value="maternal" <?php if($arrData['type'] == 'maternal'){echo "selected";} ?> >母包</option>
                        <option value="official_site" <?php if($arrData['type'] == 'official_site'){echo "selected";} ?>>多肉游戏官网</option>
                        <option value="pgyer" <?php if($arrData['type'] == 'pgyer'){echo "selected";} ?>>蒲公英</option>
                        <option value="wechat" <?php if($arrData['type'] == 'wechat'){echo "selected";} ?>>微信渠道</option>
                        <option value="zol" <?php if($arrData['type'] == 'zol'){echo "selected";} ?>>zol软件</option>
                        <option value="onlinedown" <?php if($arrData['type'] == 'onlinedown'){echo "selected";} ?>>华军软件园</option>
                        <option value="wishdown" <?php if($arrData['type'] == 'wishdown'){echo "selected";} ?>>心愿下载</option>
                        <option value="xiaopi" <?php if($arrData['type'] == 'xiaopi'){echo "selected";} ?>>小皮下载</option>
                        <option value="yyxt" <?php if($arrData['type'] == 'yyxt'){echo "selected";} ?>>优优下载</option>
                        <option value="pc6" <?php if($arrData['type'] == 'pc6'){echo "selected";} ?>>pc6下载站</option>
                        <option value="hao123" <?php if($arrData['type'] == 'hao123'){echo "selected";} ?>>hao123下载站</option>
                        <option value="downxia" <?php if($arrData['type'] == 'downxia'){echo "selected";} ?>>当下软件园</option>
                        <option value="33lc" <?php if($arrData['type'] == '33lc'){echo "selected";} ?>>绿茶软件开放平台</option>
                        <option value="ddooo" <?php if($arrData['type'] == 'ddooo'){echo "selected";} ?>>多多软件站</option>
                        <option value="u9u9" <?php if($arrData['type'] == 'u9u9'){echo "selected";} ?>>U9软件分发平台</option>
                        <option value="crsky" <?php if($arrData['type'] == 'crsky'){echo "selected";} ?>>非凡下载站</option>
                    </select>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <input type="submit" class="layui-btn" value="立即提交">
                </div>
            </div>
        </div>
    </form>
    <script src="/public/js/jquery.js"></script>
    <script src="/public/layui/layui.all.js"></script>
</body>
</html>
