<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>游戏盒子APP后台管理-新闻添加</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addnews.css?v=2010" rel="stylesheet" />
    <style>

        ul {display: none;height: 150px;overflow: auto}
    </style>
</head>
<body>
<form class="layui-form" action="/index/editnews" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">新闻添加</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">标题</label>
            <div class="layui-input-inline">
                <input type="text" name="title" placeholder="请输入标题" autocomplete="off" class="layui-input" value="<?=$data->title?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">作者</label>
            <div class="layui-input-inline">
                <input type="text" name="author" placeholder="请输入作者" autocomplete="off" class="layui-input" value="<?=$data->author?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">新闻分类</label>
            <div class="layui-input-inline">
                <select name="type">
                   <?php foreach ($newstype as $key=>$value): ?>
                        <option value="<?=$value->id?>" <?php if($value->id==$data->type){echo "selected";}?>><?=$value->type?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">推荐位</label>
            <div class="layui-input-inline" style="width: 500px;margin-bottom: 20px;">
                <input type="checkbox" name="position[]" lay-skin="primary" title="首页推荐" value="1" <?php if($data->one==1) echo "checked";?>>
                <input type="checkbox" name="position[]" lay-skin="primary" title="列表推荐" value="2" <?php if($data->two==1) echo "checked";?>>
                <input type="checkbox" name="position[]" lay-skin="primary" title="频道推荐" value="3" <?php if($data->three==1) echo "checked";?>>
            </div>
        </div>
        
        <div class="layui-form-item">
            <label class="layui-form-label">游戏名称</label>
            <div class="layui-input-inline">
                <select name="game_id"  lay-search="" lay-filter="game">
                    <option value="0">直接选择或搜索选择</option>
                    <?php foreach ($gametype as $k=>$v): ?>
                        <option value="<?=$v['id']?>" <?php if($v['id']==$data->game_id){echo "selected";}?>><?=$v['game_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">点赞数</label>
            <div class="layui-input-inline">
                <input type="number" name="click" placeholder="请输入点赞数" autocomplete="off" class="layui-input" value="<?=$data->click?>" >
            </div>
        </div>
        <div class="layui-form-item layui-form-text" id="textarea">
            <label class="layui-form-label">文章内容</label>
            <div class="layui-input-block">
                <textarea name="content" id="editor" style="display: none;"><?=$data->content?></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="hidden" value="<?=$data->id?>" name="id">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    layui.use('layedit', function(){
        var layedit = layui.layedit;
        layedit.set({
            uploadImage: {
                url: '/index/upload' //接口url
                ,type: 'post' //默认post
            },
        });
        layedit.build('editor');
        /*layedit.build('editor',{
            tool: ['strong','italic','underline','del','left','center','right','link','unlink','face','image','code','video'],
            uploadImage: {url: '/admin/upload', type: 'post'}
        });*/
    });

    //video
    /*var xhrOnProgress=function(fun) {
        console.log("xhrOnProgress")
        xhrOnProgress.onprogress = fun; //绑定监听
        //使用闭包实现监听绑
        return function() {
            //通过$.ajaxSettings.xhr();获得XMLHttpRequest对象
            var xhr = $.ajaxSettings.xhr();
            //判断监听函数是否为函数
            if (typeof xhrOnProgress.onprogress !== 'function')
                return xhr;
            //如果有监听函数并且xhr对象支持绑定时就把监听函数绑定上去
            if (xhrOnProgress.onprogress && xhr.upload) {
                xhr.upload.onprogress = xhrOnProgress.onprogress;
            }
            return xhr;
        }
    };*/


    function show(tag) {
        switch (tag){
            case 1:
                $("#textarea").css('display','block');
                $("#item1 input").removeAttr("disabled");
                $("#item2 input").attr("disabled","disabled");
                $("#item3 input").attr("disabled","disabled");
                break;
            case 2:
                $("#textarea").css('display','block');
                $("#item2 input").removeAttr("disabled");
                $("#item1 input").attr("disabled","disabled");
                $("#item3 input").attr("disabled","disabled");
                break;
            case 3:
                $("#textarea").css('display','none');
                $("#item3 input").removeAttr("disabled");
                $("#item1 input").attr("disabled","disabled");
                $("#item2 input").attr("disabled","disabled");
                break;
        }
    }
</script>
</body>
</html>
