<!doctype html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>游戏盒子APP后台管理-添加连续签到</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addmembergift.css?v201932514" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="/index/editmemberweek" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">签到编辑</div>
    <div class="layui_body" style="margin-top: 10px;">
        <div class="layui-form-item">
            <label class="layui-form-label">会员等级</label>
            <div class="layui-input-inline">
                <select lay-filter="" name="level" required>
                    <option value="0">通用等级</option>
                    <option value="1" <?php if($arrData['level']==1) echo "selected";?>>V1</option>
                    <option value="2" <?php if($arrData['level']==2) echo "selected";?>>V2</option>
                    <option value="3" <?php if($arrData['level']==3) echo "selected";?>>V3</option>
                    <option value="4" <?php if($arrData['level']==4) echo "selected";?>>V4</option>
                    <option value="5" <?php if($arrData['level']==5) echo "selected";?>>V5</option>
                    <option value="6" <?php if($arrData['level']==6) echo "selected";?>>V6</option>
                    <option value="7" <?php if($arrData['level']==7) echo "selected";?>>V7</option>
                    <option value="8" <?php if($arrData['level']==8) echo "selected";?>>V8</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">积分</label>
            <div class="layui-input-inline">
                <input type="text" name="point" placeholder="请输入签到积分" class="layui-input" value="<?=$arrData['point']?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">优惠券</label>
            <?php foreach ($arr as $k=>$v):?>
                <div class='layui-input-inline lay-inputimg' style="width: 100px;">
                    <div class='coupon' onclick='chk(this,this.dataset.iconid)' data-iconid="<?=$v['id']?>">
                        <img src='/public/img/index/6yuan_beijing.png' width='100' height='50'  />
                        <?php if($v['id'] == $arrData['coupon_id']): ?>
                            <span style="display: inline-block; width: 100px; height: 50px; background: url(&quot;/public/img/index/selcet_djq.png&quot;) 0% 0% / 100px 50px; position: absolute; z-index: 99; top: 0px; left: 0px;"></span>
                        <?php else: ?>
                            <span style='display: none; width: 100px; height: 50px;background: url(/public/img/index/selcet_djq.png);'></span>
                        <?php endif; ?>
                        <p style="position: absolute; top: 26%; left: 12%; color: white; font-weight: bold;">￥<?=$v['amount']?> 代金卷</p>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class='layui-input-inline lay-inputimg' style="width: 100px;">
                <div class='coupon' onclick='chk(this,this.dataset.iconid)' data-iconid="0">
                    <img src='/public/img/index/6yuan_beijing.png' width='100' height='50'  />
                    <span style='display: none; width: 100px; height: 50px;background: url(/public/img/index/selcet_djq.png);'></span>
                    <p style="position: absolute; top: 26%; left: 12%; color: white; font-weight: bold;">不选</p>
                </div>
            </div>
            <input type='hidden' id='coupon_id' name='coupon_id' value='<?=$arrData['coupon_id']?>'>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">游戏名称</label>
            <div class="layui-input-inline">
                <select name="game_id" lay-verify="required" lay-search="" lay-filter="game">
                    <option value="0">请选择礼包对应的游戏</option>
                    <?php foreach ($game as $k=>$v): ?>
                        <option  value='<?=$v['id']?>'  <?php if($v['id']==$arrData['game_id']) echo "selected";?>><?=$v['game_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">礼包</label>
            <div class="layui-input-inline" id="gift">
                <select name="gift_id" >
                    <option value="0">请选择礼包</option>
                    <?php foreach ($gift as $k=>$v): ?>
                        <option value="<?=$v['id']?>" <?php if($v['id']==$arrData['gift_id']) echo "selected";?>><?=$v['giftbag_name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">平台币</label>
            <div class="layui-input-inline">
                <input type="text" name="balance" placeholder="请输入平台币" autocomplete="off" class="layui-input" value="<?=$arrData['balance']?>">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="hidden" value="<?=$arrData['id']?>" name="id">
                <input type="submit" class="layui-btn" value="立即提交" />
            </div>
        </div>

    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    function chk(that,data) {
        $(".coupon span").css("display","none");
        $(that).find("span").css({"display":"inline-block","position":"absolute","z-index":"99","top":"0","left":"0","backgroundSize":"100px 50px"});
        $("#coupon_id").val(data);
    }
    layui.use(['form', 'layedit', 'laydate'], function(){
        var form = layui.form;
        form.on('select(game)', function(tag){
            var httpurl = "http://127.0.0.1:20085";
            $.get("/index/getgiftbag",{game_id:tag.value},function(msg){
                var data=$.parseJSON(msg);
                var options='<select style=" display: block;padding-right: 30px;cursor: pointer;height: 38px;line-height: 1.3;line-height: 38px;border-width: 1px;' +
                    'border-style: solid;background-color: #fff;border-radius: 2px;width: 100%; " name="gift_id">  <option value="0">请选择礼包</option>';
                for(var i=0;i<data.length;i++)
                {
                    options=options+"<option value='"+data[i].id+"'>"+data[i].giftbag_name+"</option>";
                }
                options=options+"</select>";
                $("#gift").html(options);
            })
        });
    });
</script>
</body>
</html>


