<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多肉盒子APP后台管理-新闻列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css?v=20193201138" rel="stylesheet" />
    <link href="/public/css/index/newslist.css?=201812312111" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="/admin/newssearch" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题文档</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入标题文档" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-search">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
            <div class="layui-inline">
                <button type="button" class="layui-btn layui-btn-normal">
                    <a href="addnews" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增文章</span></a>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>标题</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>创建者</span></div></th>
                    <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>点赞量</span></div></th>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>分类</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>游戏名称</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>推荐位</span></div></th>
                    <th class="laytable-cell-1-0-7"><div class="layui-table-cell"><span>添加时间</span></div></th>
                    <th class="laytable-cell-1-0-8 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($newData as $key=>$value): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value['title']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['author']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['click']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=get_news_type($value['type'])?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>
                                <?php
                                if(!empty($value['game_id']))
                                {
                                   echo  get_game_name($value['game_id']);
                                }
                                else
                                {

                                }
                                ?>

                            </span>
                        </div></td>
                    <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=($value['position'] == 1)?"首页推荐":(($value['position'] == 2)?"列表推荐":"频道推荐")?></span></div></td>
                    <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=date("Y-m-d",$value['create_time'])?></span></div></td>
                    <td class="laytable-cell-1-0-8"><div class="layui-table-cell">
                            <span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href='/index/editnews?id=<?=$value['id']?>'">编辑</span>
                            <span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$value['id']?>" onclick="window.location.href='/index/delnews?id=<?=$value['id']?>'">删除</span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
