<?php error_reporting(0); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Refresh" content="3; url=http://app.zhishengwh.com/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="404页面不存在，404页面不存在，宠爱404页面不存在">
    <meta name="description" content="">
    <title>404页面不存在</title>
    <link rel="stylesheet" href="/public/css/media/public.css">
    <link rel="stylesheet" href="/public/css/media/base.css">
    <link rel="stylesheet" href="/public/css/media/about/error.css">
</head>
<body>
<!--    公共头部    -->
<?php // load_view("inc/header");?>
<div class="header about-top news-top">
    <!--  header  -->
    <div class="nav-bar">
        <div class="main">
            <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
            <ul class="nav">
                <li class="cur"><a href="/index/index">首页</a></li>
                <li class="head-about"><a href="/index/news">宠爱动态</a></li>
                <li class="head-about"><a href="/index/rescue">宠爱救助站</a></li>
                <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>
                <li class="head-about"><a href="/index/about">关于宠爱</a></li>
                <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
            </ul>
        </div>
    </div>
</div>
<!--    404    -->
<div class="container" style="text-align: center;margin-top: 100px;">
    <img class="dib" src="/public/images/common/no_some.png" height="102" width="96" style="vertical-align: middle;margin-right: 20px;" alt="">
    <span style="font-size: 30pt;color: #FFE8CD;vertical-align: middle;">404页面不存在</span>
</div>
<!--  contact us  -->
<div class="contact-us">
    <div class="center">
        <div class="ewm"><img src="/public/img/media/index/ewm.png">多肉游戏官方公众号</div>
        <div class="adress">
            <div class="tit">深圳总公司：</div>
            <p class="ad1">广东省深圳市南山区兰香一街海王星辰总部大厦13楼
                <a href="javascript:;" class="phone">电话：+0755-86659665</a>
                <span class="email">电子邮箱：<a href="mailto:duan@mail.zhishengwh.com">duan@mail.zhishengwh.com</a></span>
            </p>
        </div>
    </div>
</div>

<!--  回到顶部  -->
<a class="go-top">返回顶部</a>

<!--  footer  -->
<div class="footer">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved<a href="http://www.miitbeian.gov.cn" target="_blank" rel="nofollow">粤ICP备18083935号</a></div>

<script src="/public/js/jquery.js"></script>
<script src="/public/js/media.js"></script>
</body>
</html>
