<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/website/mobile/css/swiper.min.css">
    <link rel="stylesheet" href="/website/mobile/css/index.css">
    <script src="/website/mobile/js/rem.js"></script>
</head>
<body>
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide part1">
                <div class="more_icon"><img src="/website/mobile/images/more_icon.png" width="5%" alt=""></div>
                <div class="next"></div>
                <div class="btn down_btn">
                    <img src="/website/mobile/images/down_icon.png" width="60%" alt="">
                </div>
            </div>

            <div class="swiper-slide part2 down_btn">
                <div class="next"></div>
            </div>

            <div class="swiper-slide part3 down_btn">
                <div class="next"></div>
            </div>

            <div class="swiper-slide part4 down_btn">
                <div class="next"></div>
            </div>

            <div class="swiper-slide part5 down_btn">
                <div class="next"></div>
            </div>

            <div class="swiper-slide part6 down_btn">
                <div class="next"></div>
            </div>

        </div>


    </div>

    <!-- more蒙版 -->
    <div class="mask" onclick="mask()">
        <p class="triangle_border_up"></p>
        <ul class="mask_box">
            <li><a href="/website/mobile_about">关于宠爱</a></li>
            <li><a href="/website/mobile_contactus">联系我们</a></li>
        </ul>
    </div>
    <script src="/website/mobile/js/jquery.min.js"></script>
    <script src="/website/mobile/js/swiper.min.js"></script>
    <script src="/website/mobile/js/index.js"></script>
</body>
</html>
