<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>玩转盒子APP后台管理-添加推送</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/addsysnotice.css" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">推送添加</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">推送标题</label>
            <div class="layui-input-inline">
                <input type="text" name="title" placeholder="请输入推送标题" autocomplete="off" class="layui-input" style="width:800px">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">推送内容</label>
            <div class="layui-input-inline">
                <input type="text" name="content" placeholder="请输入推送内容" autocomplete="off" class="layui-input" style="width:800px">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">推送图标</label>
            <div class="layui-input-inline">
                <input type="file" name="icon" value="" class="lay-input-img">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">跳转地址</label>
            <div class="layui-input-inline">
                <input type="text" name="url" autocomplete="off" readonly class="layui-input" value="wanzhuan://gamebox/notification_list" style="width:800px">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
