<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/website/mobile/css/swiper.min.css">
    <link rel="stylesheet" href="/website/pc/css/video-js.min.css">
    <link rel="stylesheet" href="/website/pc/css/index.css">
</head>
<body>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide part1">
            <div class="video-box">
                <div class="m-index-mask">
                    <div class="m-logo"><img src="/website/pc/images/logo.png" alt=""></div>
                </div>
                <video id="my-video" class="video-js" controls preload="auto" width="100%" autoplay="autoplay" loop="loop" muted poster="" data-setup="{}">
                    <source src="/website/pc/images/cazj.mp4" type="video/mp4">
                </video>
            </div>
            <div class="next"></div>
        </div>

        <div class="swiper-slide part2 down_btn">
            1
            <div class="next"></div>
        </div>

        <div class="swiper-slide part3 down_btn">
            2
            <div class="next"></div>
        </div>

        <div class="swiper-slide part4 down_btn">
            3
            <div class="next"></div>
        </div>

        <div class="swiper-slide part5 down_btn">
            4
            <div class="next"></div>
        </div>

        <div class="swiper-slide part6 down_btn">
            5
            <div class="next"></div>
        </div>

    </div>


</div>

<script src="/website/pc/js/jquery.min.js"></script>
<script src="/website/pc/js/swiper.min.js"></script>
<script src="/website/pc/js/video.min.js"></script>
<script src="/website/pc/js/index.js"></script>
</body>
</html>
