<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家-添加更新</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/pages/css/profile.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/apps/css/ticket.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
<!--  公共头部  -->
<?php $this->view->partial("inc/header")?>
<div class="clearfix"> </div>
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!--  公共左部  -->
        <?php $this->view->partial("inc/left")?>
    </div>
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-head">
                <div class="page-title">
                    <h1>添加更新</h1>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <a href="/index">主页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span class="active">二级</span>
                </li>
            </ul>
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light bordered">
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <div class="tab-pane active">
                                        <form role="form" action="" method="post" enctype="multipart/form-data">
                                            <input type="hidden" name="id" value="">
                                            <div class="form-group">
                                                <label class="control-label">APP版本号</label>
                                                <input type="text" name="version_number" placeholder="请输入APP版本号" class="form-control" value="">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">APP版本名字</label>
                                                <input type="text" name="version_name" placeholder="请输入APP版本名字" class="form-control" value="">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">是否强制更新</label>
                                                <div class="col-md-12" style="padding: 0;padding-bottom: 20px;">
                                                    <select class="bs-select form-control" name="is_forced_update">
                                                        <option value="1">是</option>
                                                        <option value="0">否</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">更新地址</label>
                                                <div style="overflow: hidden;">
                                                    <div class="col-md-12" style="padding-left: 0;float: initial;display: inline-block;padding-right: 0;width: 100%;">
                                                        <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%;">
                                                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 200px;text-align: left;"></div>
                                                            <div>
                                                            <span class="btn red btn-outline btn-file">
                                                                <span class="fileinput-new">选择文件</span>
                                                                <span class="fileinput-exists">更换文件</span>
                                                                <input type="file" name="update_address[]"> </span>
                                                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">删除</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">APP更新内容</label>
                                                <textarea class="form-control" name="update_content"  rows="5" placeholder="请输入APP更新内容"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">渠道标识</label>
                                                <div class="col-md-12" style="padding: 0;padding-bottom: 20px;">
                                                    <select class="bs-select form-control" name="type">
                                                        <option value="official_site">宠爱官网</option>
                                                        <option value="pgyer">蒲公英</option>
                                                        <option value="wechat">微信渠道</option>
                                                        <option value="qihu360">360手机助手</option>
                                                        <option value="yingyongbao">应用宝</option>
                                                        <option value="wandoujia">豌豆荚</option>
                                                        <option value="baidu">百度手机助手</option>
                                                        <option value="xiaomi">小米</option>
                                                        <option value="meizu">魅族</option>
                                                        <option value="lenovo">联想</option>
                                                        <option value="oppo">OPPO</option>
                                                        <option value="huawei">华为</option>
                                                        <option value="vivo">VIVO</option>
                                                        <option value="oneplus">一加</option>
                                                        <option value="samsung">三星</option>
                                                        <option value="smaritsan">锤子</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="margiv-top-10">
                                                <button type="submit" class="btn green">提交</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="/assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/profile.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
<script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
</body>
</html>
