<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家-去发货</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/pages/css/profile.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/apps/css/ticket.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
<!--  公共头部  -->
<?php $this->view->partial("inc/header")?>
<div class="clearfix"> </div>
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!--  公共左部  -->
        <?php $this->view->partial("inc/left")?>
    </div>
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-head">
                <div class="page-title">
                    <h1>去发货</h1>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <a href="/index">主页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span class="active">二级</span>
                </li>
            </ul>
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light bordered">
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <div class="tab-pane active">
                                        <form role="form" action="" method="post" enctype="multipart/form-data">
                                            <div class="form-group">
                                                <p style="height: 34px;background: #666;color: #fff;line-height: 34px;">商品信息</p>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">商品名称</label>
                                                <input type="text" name="" value="<?=$data['shop_name']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">商品单价（元）</label>
                                                <input type="text" name="" value="<?=$data['shop_price']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">商品数量</label>
                                                <input type="text" name="" value="<?=$data['shop_num']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">付款金额</label>
                                                <input type="text" name="" value="<?=$data['shop_total_price']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">下单时间</label>
                                                <input type="text" name="" value="<?=date("Y-m-d H:i:s",$data['pay_time'])?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <p style="height: 34px;background: #666;color: #fff;line-height: 34px;">用户信息</p>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">收件人</label>
                                                <input type="text" name="" value="<?=$data['user_name']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">联系方式</label>
                                                <input type="number" name="" value="<?=$data['user_tel']?>" readonly class="form-control">
                                            </div>
                                            <?php $address = explode(" ",$data['user_location']); ?>
                                            <div class="form-group">
                                                <label class="control-label">省市区</label>
                                                <input type="text" name="" value="<?=$address[0]?><?=$address[1]?><?=$address[2]?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">详细地址</label>
                                                <input type="text" name="" value="<?=$address[3]?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <p style="height: 34px;background: #666;color: #fff;line-height: 34px;">物流信息</p>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">订单号</label>
                                                <input type="text" name="out_trade_no" value="<?=$data['out_trade_no']?>" readonly class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12" style="padding: 0;">
                                                    <label for="span_small" class="control-label">快递公司</label>
                                                    <select id="span_small" class="form-control select2" name="express_company">
                                                        <optgroup label="直接选择或搜索快递公司">
                                                            <option value="EMS快递">EMS快递</option>
                                                            <option value="申通快递">申通快递</option>
                                                            <option value="顺丰快递">顺丰快递</option>
                                                            <option value="圆通快递">圆通快递</option>
                                                            <option value="中通快递">中通快递</option>
                                                            <option value="韵达快递">韵达快递</option>
                                                            <option value="百世汇通快递">百世汇通快递</option>
                                                            <option value="天天快递">天天快递</option>
                                                            <option value="德邦大件快递">德邦大件快递</option>
                                                            <option value="邮政">邮政</option>
                                                            <option value="京东快递">京东快递</option>
                                                        </optgroup>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">快递单号</label>
                                                <input type="text" name="express_order" placeholder="请输入快递单号" class="form-control">
                                            </div>


                                            <div class="margiv-top-10">
                                                <button type="submit" class="btn green">提交</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="/assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/profile.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
<script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/components-select2.min.js" type="text/javascript"></script>

</body>
</html>
