<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家-主页</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
    <!--  公共头部  -->
    <?php $this->view->partial("inc/header")?>

    <div class="clearfix"> </div>
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            <!--  公共左部  -->
            <?php $this->view->partial("inc/left")?>
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="page-head">
                    <div class="page-title">
                        <h1>数据统计</h1>
                    </div>
                </div>
                <ul class="page-breadcrumb breadcrumb">
                    <li><a href="/index.html">主页</a><i class="fa fa-circle"></i></li>
                    <li><span class="active">二级</span></li>
                </ul>
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="dashboard-stat2 bordered">
                            <div class="display">
                                <div class="number">
                                    <h3 class="font-green-sharp">
                                        <span data-counter="counterup" data-value="<?=$arrdata['iosall']?>"><?=$arrdata['iosall']?></span>
                                    </h3>
                                    <small>苹果端总用户数</small>
                                </div>
                                <div class="icon">
                                    <i class="icon-user"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="dashboard-stat2 bordered">
                            <div class="display">
                                <div class="number">
                                    <h3 class="font-red-haze">
                                        <span data-counter="counterup" data-value="<?=$arrdata['iosday']?>"><?=$arrdata['iosday']?></span>
                                    </h3>
                                    <small>苹果端新增用户数</small>
                                </div>
                                <div class="icon">
                                    <i class="icon-user"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="dashboard-stat2 bordered">
                            <div class="display">
                                <div class="number">
                                    <h3 class="font-blue-sharp">
                                        <span data-counter="counterup" data-value="<?=$arrdata['androidall']?>"><?=$arrdata['androidall']?></span>
                                    </h3>
                                    <small>安卓端总用户数</small>
                                </div>
                                <div class="icon">
                                    <i class="icon-user"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="dashboard-stat2 bordered">
                            <div class="display">
                                <div class="number">
                                    <h3 class="font-purple-soft">
                                        <span data-counter="counterup" data-value="<?=$arrdata['androidday']?>"><?=$arrdata['androidday']?></span>
                                    </h3>
                                    <small>安卓端新增用户数</small>
                                </div>
                                <div class="icon"><i class="icon-user"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="portlet light bordered">
                            <div class="portlet-title">
                                <div class="caption"><span class="caption-subject bold uppercase font-dark">每日新增数统计</span></div>
                            </div>
                            <div class="portlet-body">
                                <div id="echart_1" class="CSSAnimationChart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="portlet light bordered">
                            <div class="portlet-title">
                                <div class="caption "><span class="caption-subject font-dark bold uppercase">每月捐助金额统计</span></div>
                            </div>
                            <div class="portlet-body">
                                <div id="echart_3" class="CSSAnimationChart"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/assets/global/plugins/respond.min.js"></script>
    <script src="/assets/global/plugins/excanvas.min.js"></script>
    <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/moment.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/morris/morris.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/counterup/jquery.counterup.min.js" type="text/javascript"></script>
    <script src="/js/echarts.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/horizontal-timeline/horozontal-timeline.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
    <script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
    <script src="/assets/pages/scripts/dashboard.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
    <script>
        $(function(){
            //echarts每日活跃数
            var dom = document.getElementById("echart_1");
            var myChart = echarts.init(dom);
            var app = {};
            var weekdata = '<?=$arrdata['week']?>';
            var weekdata = JSON.parse(weekdata);
            console.log(weekdata)
            var week=[];
            var ios=[];
            var android=[];
            for(var i=0;i<weekdata.length;i++)
            {
                week.push(weekdata[i].day);
                ios.push(weekdata[i].ioscount);
                android.push(weekdata[i].androidcount);
            }
            console.log(ios)
            option = null;
            option = {
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data: ['安卓（Andriod）每日新增数', '苹果（Ios）每日新增数']
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                yAxis: {
                    type: 'value',
                    boundaryGap: [0, 0.01]
                },
                xAxis: {
                    type: 'category',
                    data: week
                },
                series: [
                    {
                        name: '安卓（Andriod）每日新增数',
                        type: 'bar',
                        data: ios
                    },
                    {
                        name: '苹果（Ios）每日新增数',
                        type: 'bar',
                        data: android
                    }
                ]
            };
            if (option && typeof option === "object") {
                myChart.setOption(option, true);
            }

            //每月捐助金额统计
            var dom = document.getElementById("echart_3");
            var myChart = echarts.init(dom);
            var app = {};
            option = null;
            var colors = ['#5793f3', '#d14a61'];
            var monthdata = '<?=$arrdata['month']?>';
            var year="<?=$arrdata['year']?>";
            var obj = JSON.parse(monthdata);
            var month=[];
            var alipay=[];
            var weixin=[];
            for(var i=0;i<obj.length;i++)
            {
                month.push(year+"-"+obj[i].month);
                alipay.push(obj[i].alipay_amount);
                weixin.push(obj[i].weixin_amount);
            }
            console.log(month)
            option = {
                color: colors,

                tooltip: {
                    trigger: 'none',
                    axisPointer: {
                        type: 'cross'
                    }
                },
                legend: {
                    data:['支付宝每月捐款金额', '微信每月捐款金额']
                },
                grid: {
                    top: 70,
                    bottom: 50
                },
                xAxis: [
                    {
                        type: 'category',
                        axisTick: {
                            alignWithLabel: true
                        },
                        axisLine: {
                            onZero: false,
                            lineStyle: {
                                color: colors[1]
                            }
                        },
                        axisPointer: {
                            label: {
                                formatter: function (params) {
                                    return '每月捐款金额' + params.value
                                        + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                                }
                            }
                        },
                        data: month
                    },
                    {
                        type: 'category',
                        axisTick: {
                            alignWithLabel: true
                        },
                        axisLine: {
                            onZero: false,
                            lineStyle: {
                                color: colors[0]
                            }
                        },
                        axisPointer: {
                            label: {
                                formatter: function (params) {
                                    return '每月捐款金额' + params.value
                                        + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                                }
                            }
                        },
                        data: month
                    }
                ],
                yAxis: [
                    {
                        type: 'value'
                    }
                ],
                series: [
                    {
                        name:'支付宝每月捐款金额',
                        type:'line',
                        xAxisIndex: 1,
                        smooth: true,
                        data: alipay
                    },
                    {
                        name:'微信每月捐款金额',
                        type:'line',
                        smooth: true,
                        data: weixin
                    }
                ]
            };
            if (option && typeof option === "object") {
                myChart.setOption(option, true);
            }

        })
    </script>
</body>
</html>
