<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家后台管理系统-登录</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/global/css/components.min.css" rel="stylesheet">
    <link href="/assets/pages/css/login.min.css" rel="stylesheet">
    <link href="/css/login.css" rel="stylesheet">
    <link rel="shortcut icon" href="favicon.ico">
</head>
<body class=" login">
    <div class="logo"><a href="javascript:;"><img src="/assets/pages/img/logo-big.png" alt="" /></a></div>
    <div class="content">
        <form class="login-form" action="" method="">
            <h3 class="form-title font-green">宠爱之家-后台系统</h3>
            <div class="form-group">
                <label class="control-label visible-ie8 visible-ie9">账号</label>
                <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="账号" name="username" /> </div>
            <div class="form-group">
                <label class="control-label visible-ie8 visible-ie9">密码</label>
                <input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="密码" name="password" /> </div>
            <div class="form-actions">
                <button type="submit" class="btn green uppercase">登录</button>
            </div>
        </form>
    </div>
    <div class="copyright"> 2019 © wifi.pettap.cn 深圳致晟文化创新有限公司</div>

    <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
</body>
</html>
