    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家-用户列表</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/pages/css/profile.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/apps/css/ticket.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
    <!--  公共头部  -->
    <?php $this->view->partial("inc/header")?>
    <div class="clearfix"> </div>
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
            <!--  公共左部  -->
            <?php $this->view->partial("inc/left")?>
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="page-head">
                    <div class="page-title">
                        <h1>APP用户</h1>
                    </div>
                </div>
                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <a href="/index.html">主页</a>
                        <i class="fa fa-circle"></i>
                    </li>
                    <li>
                        <span class="active">二级</span>
                    </li>
                </ul>
                <div class="row">
                    <div class="col-md-12">
                        <div class="app-ticket app-ticket-list">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="portlet light bordered">
                                        <div class="portlet-title">
                                            <div class="caption font-dark">
                                                <i class="icon-settings font-dark"></i>
                                                <span class="caption-subject bold uppercase">用户列表</span>
                                            </div>
                                            <div class="tools"> </div>
                                        </div>
                                        <div class="portlet-body">
                                            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                                                <thead>
                                                <tr>
                                                    <th>
                                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                            <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                                            <span></span>
                                                        </label>
                                                    </th>
                                                    <th>ID</th>
                                                    <th>手机号</th>
                                                    <th>宠爱号</th>
                                                    <th>昵称</th>
                                                    <th>性别</th>
                                                    <th>用户分类</th>
                                                    <th>用户分组</th>
                                                    <th>用户等级</th>
                                                    <th>注册时间</th>
                                                    <th>最近登陆时间</th>
                                                    <th>注册IP</th>
                                                    <th>锁定状态</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach ($arrdata as $k=>$v): ?>
                                                <tr class="odd gradeX">
                                                    <td>
                                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                            <input type="checkbox" class="checkboxes" value="<?=$v['id']?>" />
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                    <td><?=$v['id']?></td>
                                                    <td><?=$v['mobile_num']?></td>
                                                    <td><?=$v['uid']?></td>
                                                    <td><?=$v['nick_name']?></td>
                                                    <td><?=$v['sex']?></td>
                                                    <td><?=$v['type']?></td>
                                                    <td><?=$v['competence']?></td>
                                                    <td><?=$v['user_level']?></td>
                                                    <td><?=date("Y-m-d H:i:s",$v['register_time'])?></td>
                                                    <td><?=date("Y-m-d H:i:s",$v['last_activity_date'])?></td>
                                                    <td><?=$v['register_ip']?></td>
                                                    <td><input type="checkbox" <?php if($v['lock_status']==1){echo "checked";}?> class="make-switch select_check"  data-size="small"
                                                               name="status" data-userid="<?=$v['id']?>" ></td>
                                                </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="/assets/global/plugins/respond.min.js"></script>
    <script src="/assets/global/plugins/excanvas.min.js"></script>
    <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <script src="/assets/global/scripts/datatable.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
    <script src="/assets/pages/scripts/table-datatables-buttons.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
    <script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>

    <script>
     /*  $(".select_check").click(function(){
                var id = $(this).data('userid');
                alert(id);return;
                var that = $(this);
                var status = $(this).find('input').attr('name');
                if(status == 'close'){
                    status = '1';
                    $.get('/user/useredit',{id:id,status:status},(msg)=>{
                        if(msg.msg == 'ok'){
                            layer.msg('修改成功', {icon: 6});
                            that.find('input').attr('checked','checked');
                            that.find('input').attr('name','open');
                        }else{
                            layer.msg('修改失败', {icon: 5});
                        }
                    },"json")
                }else{
                    status = '0';
                    $.get('/user/useredit',{id:id,status:status},(msg)=>{
                        if(msg.msg == 'ok'){
                            layer.msg('修改成功', {icon: 6});
                            that.find('input').removeAttr('checked');
                            that.find('input').attr('name','close');
                        }else{
                            layer.msg('修改失败', {icon: 5});
                        }
                    },"json")
                }
            });*/
     $('[name="status"]').bootstrapSwitch({
         onSwitchChange:function(event,state){
             id=$(this).data('userid');
             if(state==true){
                 status = 1;
                 $.post("/admin/useredit",{id:id,status:status},function(result){
                     if(result==0)
                     {
                         alert("修改成功");
                     }
                     else{
                         alert("修改失败");
                     }
                 });
             }else{
                 status = 0;
                 $.post("/admin/useredit",{id:id,status:status},function(result){
                     if(result==0)
                     {
                         alert("修改成功");
                     }
                     else{
                         alert("修改失败");
                     }
                 });
             }
         }

     });

    </script>
</body>
</html>
