<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-词语过滤</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/commonweal/monweallist.css" rel="stylesheet" />
</head>
<body>
    <div class="layui-form layui-card-header layuiadmin-card-header-auto">
        <form action="" method="">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button type="button" class="layui-btn layui-btn-normal">
                        <a href="addmonweal" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">发布公益项目</span></a>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="layui-form layui-border-box layui-table-view">
        <div class="layui-table-box">
            <div class="layui-table-header">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <thead>
                    <tr>
                        <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                        <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>标题</span></div></th>
                        <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>目标金额（元）</span></div></th>
                        <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>已筹金额（元）</span></div></th>
                        <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>捐款次数</span></div></th>
                        <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>发布时间</span></div></th>
                        <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>操作</span></div></th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="layui-table-body layui-table-main">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <tbody id="list_body">
                        <?php foreach ($arrData as $key=>$value): ?>
                        <tr>
                            <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                            <td class="laytable-cell-1-0-1">
                                <div class="layui-table-cell">
                                    <span><?=$value['title']?>
                                        <?php
                                            if($value['is_urgent']==0)
                                            {
                                                echo "<span style='color: #00cc00'>(非紧急)</span>";
                                            }
                                            else{
                                                echo "<span style='color: red'>(紧急)</span>";
                                            }
                                        ?>
                                    </span>
                                </div>
                            </td>
                            <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['target_amount']?></span></div></td>
                            <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['raised_amount']?></span></div></td>
                            <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$value['donation_sum']?></span></div></td>
                            <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=date("Y-m-d",$value['create_time'])?></span></div></td>
                            <td class="laytable-cell-1-0-6">
                                <div class="layui-table-cell">
                                    <span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href = '/commonweal/monwealedit?id=<?=$value['id']?>'">编辑</span>
                                    <span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$value['id']?>" onclick="del(this)">删除</span>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
    <script>
        let del = (tag)=>{
            let id = $(tag).data('id');
            $.get("/commonweal/monwealdel",{id:id},(msg)=>{
                if(msg.msg == 'ok'){
                    window.location.href = "/commonweal/monweallist";
                }else{
                    layer.msg('删除失败', {icon: 5});
                }
            },"json");
        }
    </script>
</body>
</html>
