<!--  contact us  -->
<div class="contact-us">
    <div class="center">
        <div class="ewm"><img src="/public/img/media/index/ewm.png">宠爱之家官方公众号</div>
        <div class="ewm"><img src="/public/img/media/index/wechat.jpg">宠爱之家官方微信号</div>
        <div class="adress">
            <div class="tit">深圳总公司：</div>
            <p class="ad1">广东省深圳市南山区兰香一街海王星辰总部大厦13楼
                <a href="javascript:;" class="phone">客服QQ：2705180242</a>
                <span class="email">电子邮箱：<a href="mailto:2705180242@qq.com">2705180242@qq.com</a></span>
            </p>
        </div>
    </div>
</div>

<!--  回到顶部  -->
<a class="go-top">返回顶部</a>

<!--  footer  -->
<div class="footer">Copyright © 2019 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved<a href="http://www.miitbeian.gov.cn" target="_blank" rel="nofollow">粤ICP备18083935号</a></div>
