<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-修改banner</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/banneradd.css" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="/admin/banneredit" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">banner添加</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">banner</label>
            <div class="layui-input-inline">
                <input type="file" accept="image/*" name="banner" class="layui-input">
                <img class="layui-table-img" src="/public<?=$userData['pic']?>" width="100px" height="50px">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">地址</label>
            <div class="layui-input-inline">
                <input type="url" name="url" value="<?=$userData['url']?>">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="hidden" name="id" value="<?=$userData['id']?>">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
