<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-首页Banner</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/index/banner.css?=2018122120" rel="stylesheet" />
</head>
<body>
    <div class="layui-form layui-card-header layuiadmin-card-header-auto">
        <form action="/user/usersearch" method="get">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button type="button" class="layui-btn layui-btn-normal">
                        <a href="banneradd" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增banner</span></a>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="layui-form layui-border-box layui-table-view">
        <div class="layui-table-box">
            <div class="layui-table-header">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <thead>
                    <tr>
                        <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                        <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>banner展示(690px * 180px)</span></div></th>
                        <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>地址</span></div></th>
                        <th class="laytable-cell-1-0-3 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="layui-table-body layui-table-main">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <tbody id="list_body">
                    <?php foreach ($page as $key=>$value): ?>
                    <tr>
                        <td class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                        <td class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><img class="layui-table-img" src="/public<?=$value['pic']?>" alt=""></div></td>
                        <td class="layui-unselect laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['url']?></span></div></td>
                        <td class="layui-unselect laytable-cell-1-0-3"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-danger" onclick="window.location.href = '/admin/banneredit?id=<?=$value['id']?>'">修改</span></div></td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="/public/js/jquery.js"></script>
    <script src="/public/layui/layui.all.js"></script>
</body>
</html>
