<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>宠爱之家APP后台管理-主页</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <style>
        .layui-nav-tree .layui-nav-item > a{height: 54px;line-height: 54px;}
        .layui-nav-child a{padding: 0 44px!important;}
        .layui-tab-close{display: none!important;}
        .layui-tab-title li a{display: inline-block;color: #000!important; font-size: 14px;}
        .layui-icon-link{font-size: 12px;padding: 0 10px;}
        .layui-tab-title .layui-this:after{border-style: none!important;}
        .layui-tab-content{overflow: hidden;padding: 5px;}
        .layui-tab-item{overflow: hidden;}
        .layui-col-xs3 ,.layui-col-xs6{padding: 5px;}
        .layui-card-body{display: flex;justify-content: center;flex-direction: column;text-align: center;height: 160px;}
        .layui_card_box{flex-direction: row;align-items: center;}
        .echarts_view{height: 400px;}
        .layui-card-header{font-weight: 600;}
        .date_box{padding: 5px 0;color: #009688;}
        .num_box{padding: 10px 0;}
        .num{font-size: 28px;color: #ff4545;}
    </style>
</head>
<body>
<div class="layui-layout-admin">
    <!--头部-->
    <div class="layui-header">
        <div class="layui-logo"><img src="/public/img/common/logo.png" width="200" height="40" alt="" style="margin-top: -1px;"></div>
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item layui-hide-xs" lay-unselect>
                <a href="http://www.pettap.cn" target="_blank" title="前台">
                    <i class="layui-icon layui-icon-website"></i>
                </a>
            </li>
            <li class="layui-nav-item" lay-unselect>
                <a href="javascript:;" layadmin-event="refresh" title="刷新">
                    <i class="layui-icon layui-icon-refresh-3"></i>
                </a>
            </li>
            <li class="layui-nav-item layui-hide-xs" lay-unselect>
                <input type="text" placeholder="搜索..." autocomplete="off" class="layui-input layui-input-search" layadmin-event="serach" lay-action="template/search/keywords=">
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item" lay-unselect>
                <a lay-href="app/message/" layadmin-event="message">
                    <i class="layui-icon layui-icon-notice"></i>
                    <!-- 如果有新消息，则显示小圆点 -->
                </a>
            </li>
            <li class="layui-nav-item layui-hide-xs" lay-unselect>
                <a href="javascript:;" layadmin-event="fullscreen" id="fullScreen">
                    <i class="layui-icon layui-icon-screen-full"></i>
                </a>
            </li>
            <li class="layui-nav-item layui-hide-xs" lay-unselect>
                <a href="javascript:;" layadmin-event="note">
                    <i class="layui-icon layui-icon-note"></i>
                </a>
            </li>
            <li class="layui-nav-item">
                <a href="javascript:void(0);"><img src="http://m.zhengjinfan.cn/images/0.jpg" class="layui-nav-img"><?=$username?></a>
                <dl class="layui-nav-child">
                    <dd><a href="">基本资料</a></dd>
                    <dd><a href="">修改密码</a></dd>
                    <dd><a href="/login/logout">安全退出</a></dd>
                </dl>
            </li>
        </ul>
    </div>

    <!--左侧-->
    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <ul class="layui-nav layui-nav-tree" lay-filter="hbkNavbar">
                <?php foreach ($arr as $key=>$value): ?>
                <li class="layui-nav-item">
                    <a href="javascript:void(0);"><i class="layui-icon layui-icon-<?=$value['icon']?>" style="margin-right: 10px;"></i><?=$value['title']?></a>
                    <dl class="layui-nav-child">
                        <?php foreach ($value['data'] as $k=>$v): ?>
                        <dd><a href="javascript:;" data-options="{url:'<?=$v['url']?>',title:'<a href=\'/admin/index\'>控制台<i class=\'layui-icon layui-icon-link\'></i></a><?=$v['title']?>',id:<?=$v['id']?>}"><?=$v['title']?></a></dd>
                        <?php endforeach; ?>
                    </dl>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <!--中间主体-->
    <div class="layui-body" id="container">
        <div class="layui-tab" lay-filter="tabs" lay-allowclose="true">
            <ul class="layui-tab-title" id="layui-tab-title">
                <li><a href='/admin/index'>控制台<i class='layui-icon layui-icon-link'></i></a>主页</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <div class="layui-col-xs3">
                        <div class="layui-card">
                            <div class="layui-card-header">安卓（Andriod）DAU</div>
                            <div class="layui-card-body layui_card_box">
                                <img src="/public/img/index/andriod_dau.png" height="72" width="72" alt="" style="display: inline-block;">
                                <div>
                                    <div class="date_box"><?=date("Y-m-d",time())?></div>
                                    <div class="num_box"><span class="num"><?=$pnum?></span><span>人</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs3">
                        <div class="layui-card">
                            <div class="layui-card-header">苹果（Ios）DAU</div>
                            <div class="layui-card-body layui_card_box">
                                <img src="/public/img/index/ios_dau.png" height="72" width="72" alt="" style="display: inline-block;margin-right: 2px;">
                                <div>
                                    <div class="date_box"><?=date("Y-m-d",time())?></div>
                                    <div class="num_box"><span class="num"><?=$pnum?></span><span>人</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs3">
                        <div class="layui-card">
                            <!--<div class="layui-card-header">安卓（Andriod）新增长用户数</div>-->
                            <div class="layui-card-header">捐款微信金额</div>
                            <div class="layui-card-body layui_card_box">
                                <img src="/public/img/index/andriod_add_user.png" height="72" width="72" alt="" style="display: inline-block;margin-right: 2px;">
                                <div>
                                    <div class="date_box"><?=date("Y-m-d")?></div>
                                    <div class="num_box"><span class="num"><?=$people['weixin_count']?></span><span>元</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs3">
                        <div class="layui-card">
<!--                            <div class="layui-card-header">苹果（Ios）新增长用户数</div>-->
                            <div class="layui-card-header">捐款支付宝金额</div>
                            <div class="layui-card-body layui_card_box">
                                <img src="/public/img/index/ios_add_user.png" height="72" width="72" alt="" style="display: inline-block;margin-right: 2px;">
                                <div>
                                    <div class="date_box"><?=date("Y-m-d")?></div>
                                    <div class="num_box"><span class="num"><?=$people['alipay_count']?></span><span>元</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs6">
                        <!-- 填充内容 -->
                        <div class="layui-card">
                            <div class="layui-card-header">每日活跃用户数</div>
                            <div class="layui-card-body echarts_view">
                                <div id="echarts_date" style="height: 100%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs6">
                        <!-- 填充内容 -->
                        <div class="layui-card">
                            <!--<div class="layui-card-header">每周新增用户数</div>-->
                            <div class="layui-card-header">每月捐款金额</div>
                            <div class="layui-card-body echarts_view">
                                <div id="echarts_box" style="height: 100%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--底部-->
    <div class="layui-footer">
        <center>深圳致晟文化创新有限公司版权所有@Tel:0755-86659665</center>
    </div>
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.js"></script>
<script src="/public/js/echarts.min.js"></script>
<script>
    //JavaScript代码区域
    layui.use('element', function () {
        var element = layui.element;
        element.on('nav(hbkNavbar)', function (elem) {
            /*使用DOM操作获取超链接的自定义data属性值*/
            var options = eval('('+$(this).data('options')+')');
            var url = options.url;
            var title = options.title;
            $(".layui-tab-title").empty();
            if(title != 'nav'){
                element.tabAdd('tabs',{
                    title: title,
                    content: '<iframe scrolling="auto" frameborder="0" src="' + url + '" style="width:100%;height:100%;"></iframe>',
                    id: 'id'
                });
            }
            $(".layui-tab-content").empty();
            var docHeight = $(document).height()-168;
            console.log(docHeight);
            $("<iframe scrolling='auto' frameborder='0' src='" + url + "' style='width:100%;height:"+docHeight+"px;'></iframe>").appendTo($(".layui-tab-content"));
        });


        $("#fullScreen").toggle(
            function () {
                var el = document.documentElement;
                var rfs = el.requestFullScreen || el.webkitRequestFullScreen || el.mozRequestFullScreen || el.msRequestFullscreen;
                if(typeof rfs != "undefined" && rfs) {
                    rfs.call(el);
                };
                return;
            },
            function () {
                if (document.exitFullscreen) {
                    document.exitFullscreen();
                }
                else if (document.mozCancelFullScreen) {
                    document.mozCancelFullScreen();
                }
                else if (document.webkitCancelFullScreen) {
                    document.webkitCancelFullScreen();
                }
                else if (document.msExitFullscreen) {
                    document.msExitFullscreen();
                }
                if(typeof cfs != "undefined" && cfs) {
                    cfs.call(el);
                }
            }
        );


        //echarts每日活跃数
        var dom = document.getElementById("echarts_date");
        var myChart = echarts.init(dom);
        var app = {};
        option = null;
        option = {
            tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'shadow'
                }
            },
            legend: {
                data: ['安卓（Andriod）每日活跃数', '苹果（Ios）每日活跃数']
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            yAxis: {
                type: 'value',
                boundaryGap: [0, 0.01]
            },
            xAxis: {
                type: 'category',
                data: ['2018-12-1','2018-12-2','2018-12-3','2018-12-4','2018-12-5','2018-12-6','2018-12-7']
            },
            series: [
                {
                    name: '安卓（Andriod）每日活跃数',
                    type: 'bar',
                    data: [182303, 234829, 293034, 104970, 131744, 630230, 630230]
                },
                {
                    name: '苹果（Ios）每日活跃数',
                    type: 'bar',
                    data: [192325, 234338, 310020, 121594, 134141, 681807, 784412]
                }
            ]
        };
        if (option && typeof option === "object") {
            myChart.setOption(option, true);
        }

        //echarts每月用户数
        var dom = document.getElementById("echarts_box");
        var myChart = echarts.init(dom);
        var app = {};
        option = null;
        var colors = ['#5793f3', '#d14a61'];
        var monthdata = '<?=$monthdata?>';
        var year="<?=$year?>";
        var obj = JSON.parse(monthdata);
        var month=[];
        var alipay=[];
        var weixin=[];
        for(var i=0;i<obj.length;i++)
        {
            month.push(year+"-"+obj[i].month);
            alipay.push(obj[i].alipay_amount);
            weixin.push(obj[i].weixin_amount);
        }
      console.log(month)

        option = {
            color: colors,

            tooltip: {
                trigger: 'none',
                axisPointer: {
                    type: 'cross'
                }
            },
            legend: {
                data:['支付宝每月捐款金额', '微信每月捐款金额']
            },
            grid: {
                top: 70,
                bottom: 50
            },
            xAxis: [
                {
                    type: 'category',
                    axisTick: {
                        alignWithLabel: true
                    },
                    axisLine: {
                        onZero: false,
                        lineStyle: {
                            color: colors[1]
                        }
                    },
                    axisPointer: {
                        label: {
                            formatter: function (params) {
                                return '每月捐款金额' + params.value
                                    + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                            }
                        }
                    },
                    data: month
                },
                {
                    type: 'category',
                    axisTick: {
                        alignWithLabel: true
                    },
                    axisLine: {
                        onZero: false,
                        lineStyle: {
                            color: colors[0]
                        }
                    },
                    axisPointer: {
                        label: {
                            formatter: function (params) {
                                return '每月捐款金额' + params.value
                                    + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                            }
                        }
                    },
                    data: month
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name:'支付宝每月捐款金额',
                    type:'line',
                    xAxisIndex: 1,
                    smooth: true,
                    data: alipay
                },
                {
                    name:'微信每月捐款金额',
                    type:'line',
                    smooth: true,
                    data: weixin
                }
            ]
        };
        if (option && typeof option === "object") {
            myChart.setOption(option, true);
        }

    });

</script>
</body>
</html>
