<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-添加banner</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/merc/addreturnapply.css" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">添加申请</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">订单号</label>
            <div class="layui-input-inline">
                <select name="out_trade_no" lay-verify="required" lay-search="" lay-filter="test">
                    <option value="">直接选择或搜索选择</option>
                    <?php foreach ($data as $k=>$v): ?>
                    <option value="<?=$v['out_trade_no']?>"><?=$v['out_trade_no']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div id="order_info"></div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    layui.use(['layer', 'jquery', 'form'], function () {
        var form = layui.form;
        form.on('select(test)', function(tag){
            //console.log(data.elem); //得到select原始DOM对象
            //console.log(data.value); //得到被选中的值
            //console.log(data.othis); //得到美化后的DOM对象
            var data = tag.value;
             $("#order_info").empty();
             $.post("/merc/ajaxapply",{order:data},(msg)=>{
             let strhtml = "<div class='layui-form-item'><label class='layui-form-label'>商品名称</label><div class='layui-input-inline'>";
             strhtml += "<input type='text' name='shop_name' class='layui-input' style='width: 500px;' value='"+msg.shop_name+"'></div></div>";

             strhtml += "<div class='layui-form-item'><label class='layui-form-label'>用户姓名</label><div class='layui-input-inline'>";
             strhtml += "<input type='text' name='user_name' class='layui-input' style='width: 500px;' value='"+msg.user_name+"'></div></div>";

             strhtml += "<div class='layui-form-item'><label class='layui-form-label'>联系方式</label><div class='layui-input-inline'>";
             strhtml += "<input type='text' name='user_tel' class='layui-input' style='width: 500px;' value='"+msg.user_tel+"'></div></div>";

             strhtml += "<div class='layui-form-item'><label class='layui-form-label'>金额</label><div class='layui-input-inline'>";
             strhtml += "<input type='text' name='shop_total_price' class='layui-input' style='width: 500px;' value='"+msg.shop_total_price+"'></div></div>";
             $("#order_info").html(strhtml);
             },"json");
        });
    });
</script>
</body>
</html>
