<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-帖子列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/merc/orderlist.css?v=201904191428" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">订单号</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入订单号" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>订单号</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>收件人</span></div></th>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>联系方式</span></div></td>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>商品名称</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>商品单价（元）</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>商品数量（件）</span></div></th>
                    <th class="laytable-cell-1-0-7"><div class="layui-table-cell"><span>支付时间</span></div></th>
                    <th class="laytable-cell-1-0-8"><div class="layui-table-cell"><span>支付状态</span></div></th>
                    <th class="laytable-cell-1-0-9 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($page as $k=>$v): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['order_id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['out_trade_no']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['user_name']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$v['user_tel']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$v['shop_name']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>￥<?=$v['shop_price']?></span></div></td>
                    <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=$v['shop_num']?></span></div></td>
                    <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$v['pay_time'])?></span></div></td>
                    <td class="laytable-cell-1-0-8"><div class="layui-table-cell"><span><?=($v['pay_status'] == 0)?"未支付":"成功"?></span></div></td>
                    <td class="laytable-cell-1-0-9"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href='/merc/orderdetail?id=<?=$v['order_id']?>'">查看</span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
