<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-帖子列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/merc/shoplist.css" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">商品名称</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入商品名称" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>商品名称</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>商品品牌</span></div></th>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>商品金额</span></div></td>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>商品库存</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>使用对象</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>保质期</span></div></th>
                    <th class="laytable-cell-1-0-7 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($page as $k=>$v): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['shop_name']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['brand']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$v['price']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$v['inventory']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=$v['shop_object']?></span></div></td>
                    <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=$v['shelf_life']?></span></div></td>
                    <td class="laytable-cell-1-0-7">
                        <div class="layui-table-cell">
                            <span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$v['id']?>" onclick="shelf(this)">上架</span>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    let shelf = (tag)=>{
        let id = $(tag).data('id');
        $.get("/merc/topshop",{id:id},(msg)=>{
            if(msg.msg == 'ok'){
                window.location.href = "/merc/shoplist";
            }else{
                layer.msg('上架失败', {icon: 5});
            }
        },"json");
    }

</script>
</body>
</html>
