<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-帖子列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/merc/userlist.css?v=201904191428" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>联系人</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>联系方式</span></div></th>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>省市区</span></div></td>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>详细地址</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>用户ID</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($page as $key=>$value): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['addr_id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value['user_name']?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['user_tel']?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['user_province']?> <?=$value['user_city']?> <?=$value['user_area']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$value['user_addr']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=get_zs_user_uid($value['user_id'])?></span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
