<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="applicable-device" content="mobile">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/public/css/mpettap/sm.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1016610_yupu4u1663h.css">
    <link rel="stylesheet" href="/public/css/mpettap/reset.css">
    <link rel="stylesheet" href="/public/css/mpettap/about.css">
</head>
<body>
    <div class="page">
        <header class="bar bar-nav">
            <a href="javascript:void(0);" external class="pull-left logo"></a>
            <span class="icon iconfont icon-icon- pull-right"></span>
        </header>
        <div class="content">
            <!-- banner -->
            <div class="banner-top"></div>

            <!-- aboutus -->
            <div class="us">
                <div class="title-logo">宠爱介绍</div>
                <p>深圳致晟文化创新有限公司创始人致力于打造基于互联网的宠爱之家APP，为社会为流浪猫狗提供公益性援助，同时公司出资建立自己宠物救助站，以及联系医院，减轻社会救助站的环境及所开支问题。</p>
                <p>宠爱之家是款集领养、救援、商城、社区、聊天于一体的新型慈善APP，我们让爱心人士资金捐助更加清晰透明，让救助爱宠更加便捷，让救助基地求助渠道更加广阔，让萌宠交流更加有趣，让领养代替购买！</p>
                <p>宠爱团队衷心希望更多热爱公益事业，有爱心人士加入到宠爱之家平台上！</p>
            </div>

            <!--  关注宠爱  -->
            <div class="follow">
                <div class="contact ewm">
                    <img src="/public/images/mpettap/ewm.jpg" alt="">
                    <p>宠爱之家官方公众号</p>
                </div>
                <div class="contact">
                    <img src="/public/images/mpettap/wechat.jpg" alt="">
                    <p>宠爱之家官方微信号</p>
                </div>
            </div>

            <!--  address  -->
            <div class="address">
                <div class="address-con">
                    <div class="tit">宠爱之家深圳总部</div>
                    <p><span class="icon iconfont icon-weizhi tit-icon"></span><span>广东省深圳市南山区兰香一街海王星辰总部大厦13楼</span></p>
                    <p><span class="icon iconfont icon-dianhua tit-icon"></span><span class="add-t">客服QQ：2705180242</span><span class="icon iconfont icon-youjian tit-icon"></span><span>电子邮箱：2705180242@qq.com</span></p>
                </div>
            </div>

            <!--footer-->
            <div class="footer">
                Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved
                <a href="http://www.miitbeian.gov.cn" external rel="nofollow">粤ICP备18083935号</a>
            </div>
        </div>
    </div>

    <span class="icon iconfont icon-31huidaodingbu go-top" id="goTop"></span>

    <?php load_view("inc/wapheader");?>

    <script type='text/javascript' src='/public/js/mpettap/test.js' charset='utf-8'></script>
    <script type='text/javascript' src='/public/js/mpettap/sm.min.js' charset='utf-8'></script>
    <script type="text/javascript" src="/public/js/mpettap/index.js"></script>
</body>
</html>
