<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="applicable-device" content="mobile">
    <title>宠爱之家-查看审核</title>
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <link rel="stylesheet" href="/public/css/media/swiper.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1016610_4yrtv93dycc.css">
    <link rel="stylesheet" href="/public/css/mpettap/reset.css">
    <link rel="stylesheet" href="/public/css/mpettap/examine.css">
</head>
<body>
    <div class="page">
        <header class="bar bar-nav">
            <a href="javascript:void(0);" external class="pull-left logo"></a>
            <span class="icon iconfont icon-tuichu pull-right" onclick="window.location.href='/login/waplogin'"></span>
        </header>
        <img src="/public/images/mpettap/pt1.png" alt="">
        <!-- info -->

        <?php if($status == '0'): ?>
            <div class="info-box">
                <span class="success-icon"></span>
                <p>您的救助站信息已提交宠爱之家平台，预计审核时间为3天左右，最长审核时间为7个工作日内，在此期间请您耐心等待。</p>
            </div>
        <?php else: ?>
            <div class="info-box">
                <span class="success-icon"></span>
                <p>您的救助站信息已提交宠爱之家平台，已经通过人工审核啦...请等待宠爱之家平台商务人员跟您取得联系请确保您提交的电话保持开通。</p>
            </div>
        <?php endif; ?>

        <div class="info-box"></div>

        <div class="info-box in-b">
            <div class="i-b"><button class="info-btn" onclick="window.location.href='/wap/rescueinfo2?mobile_num=<?=$_COOKIE['mobile_num']?>'">审核进度查询</button></div>
            <div class="i-b"><button class="info-btn" onclick="window.location.href='/wap/rescueedit?mobile_num=<?=$_COOKIE['mobile_num']?>'">修改审核信息</button></div>
        </div>

        <div class="info-box"></div>
        <div class="info-box"></div>

        <div class="f-box">
            <!--  address  -->
            <div class="address">
                <div class="address-con">
                    <div class="tit">宠爱之家深圳总部</div>
                    <p><span class="icon iconfont icon-weizhi tit-icon"></span><span>广东省深圳市南山区兰香一街海王星辰总部大厦13楼</span></p>
                    <p><span class="icon iconfont icon-dianhua tit-icon"></span><span class="add-t">客服QQ：2705180242</span><span class="icon iconfont icon-youjian tit-icon"></span><span>电子邮箱：2705180242@qq.com</span></p>
                </div>
            </div>

            <!--footer-->
            <div class="footer">
                Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved
                <a href="http://www.miitbeian.gov.cn" external rel="nofollow">粤ICP备18083935号</a>
            </div>
        </div>
    </div>
    <script src="/public/js/jquery.js"></script>
</body>
</html>
