<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>玩转盒子APP后台管理-添加代金券</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/play/addplay.css?v=20193261421" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="/play/addplay" method="post" enctype="multipart/form-data">
    <div class="layui-card-header">添加代金券</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">内容</label>
            <div class="layui-input-inline">
                <input type="text" name="amount" placeholder="请输入内容" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">icon图片</label>
            <div class="layui-input-inline">
                <input type="file" name="icon" value="" class="lay-input-img">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">起始时间</label>
            <div class="layui-input-inline">
                <input type="date" id="date_info" name="start_time" class="lay-input-img start_time" max="">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">结束时间</label>
            <div class="layui-input-inline">
                <input type="date" name="end_time" class="lay-input-img end_time" min="">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" class="layui-btn" value="立即提交" min="">
            </div>
        </div>
    </div>
</form>


<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    $(function(){
        $(".start_time").change(function(){
            var start_time = $(".start_time").val();
            $(".end_time").attr('min',start_time);
        });

        $(".end_time").change(function(){
            var end_time = $(".end_time").val();
            $(".start_time").attr('max',end_time);
        });
    })
</script>
</body>
</html>
