<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多肉盒子APP后台管理-积分商城</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/play/integralmall.css?v=201904031431" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline" style="margin-left: 10px;">
                <button type="button" class="layui-btn layui-btn-normal">
                    <a href="/play/addintegralmall" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增代金券</span></a>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>使用规则</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>适用游戏</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-2"><div class="layui-table-cell"><span>兑换积分</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-3"><div class="layui-table-cell"><span>兑换券</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-4"><div class="layui-table-cell"><span>使用介绍</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-5"><div class="layui-table-cell"><span>金额(元)</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-6"><div class="layui-table-cell"><span>抵用金额(元)</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-7"><div class="layui-table-cell"><span>数量</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-8"><div class="layui-table-cell"><span>起始时间</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-9"><div class="layui-table-cell"><span>结束时间</span></div></th>
                    <th class="layui-unselect laytable-cell-1-0-10 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($arrData as $k=>$v): ?>
                <tr>
                    <td class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$v['id']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$v['userule']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['apply_game']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$v['point']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-3"><div class="layui-table-cell"><span><img class="layui-table-img" src="<?=$v['pic']?>" alt=""></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-4"><div class="layui-table-cell" ><span><?=substr($v['content'],0,30)."..."?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=$v['amount']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=$v['credit']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=$v['num']?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-8"><div class="layui-table-cell"><span><?=date("Y-m-d ",$v['start_time'])?></span></div></td>
                    <td class="layui-unselect laytable-cell-1-0-9"><div class="layui-table-cell"><span><?=date("Y-m-d ",$v['end_time'])?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell">
                            <span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href='/play/editintegralmall?id=<?=$v['id']?>'">编辑 </span>
                            <span class="layui-btn layui-btn-xs layui-btn-danger" onclick="window.location.href='/play/delintegralmall?id=<?=$v['id']?>'">删除</span>

                        </div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
