<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多肉盒子APP后台管理-充值赚积分</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/play/rechargeintegral.css?v=201942914" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="" method="get">
        <div class="layui-form-item">
            <div class="layui-inline" style="margin-left: 10px;">
                <button type="button" class="layui-btn layui-btn-normal">
                    <a href="/play/addrechargeintegral" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">新增充值赚积分</span></a>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>游戏</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>充值(元)</span></div></th>
                    <th class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>积分</span></div></th>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>会员权限</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>会员赠送福利</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>起始时间</span></div></th>
                    <th class="laytable-cell-1-0-7"><div class="layui-table-cell"><span>结束时间</span></div></th>
                    <th class="laytable-cell-1-0-8 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($arrdata as $key=>$value): ?>
                    <tr>
                        <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                        <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value['game_name']?></span></div></td>
                        <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['amount']?></span></div></td>
                        <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['point']?></span></div></td>
                        <td class="laytable-cell-1-0-4">
                            <div class="layui-table-cell">
                                <span>
                                    <?php
                                    if($value['is_member']==0)
                                    {
                                        echo "否";
                                    }
                                    else{
                                        echo "是";
                                    }
                                    ?>
                                </span>
                            </div></td>
                        <td class="laytable-cell-1-0-5"><div class="layui-table-cell">
                                <span>
                                    v1:<?=$value['v1']?>; v2:<?=$value['v2']?>; v3:<?=$value['v3']?>; v4:<?=$value['v4']?>;
                                    v5:<?=$value['v5']?>;v6:<?=$value['v6']?>; v7:<?=$value['v7']?>; v8:<?=$value['v8']?>;
                                </span>
                            </div></td>
                        <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=date("Y-m-d",$value['start_time'])?></span></div></td>
                        <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span><?=date("Y-m-d",$value['end_time'])?></span></div></td>
                        <td class="laytable-cell-1-0-8"><div class="layui-table-cell">
                                <span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href='/play/editrechargeintegral?id=<?=$value['id']?>'">
                                    编辑</span><span class="layui-btn layui-btn-xs layui-btn-danger" onclick="window.location.href='/play/delrechargeintegral?id=<?=$value['id']?>'">删除</span></div></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
