<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>多肉盒子</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-status-bar-style" content=" black ">
    <meta name="format-detection" content="telephone=no">
    <meta name="full-screen" content="yes">
    <meta name="x5-fullscreen" content="true">
    <meta name="applicable-device" content="mobile">
    <link rel="canonical" href="">
    <link href="images/favicon.ico" rel="shortcut icon">
    <link rel="stylesheet" href="/public/mobile/css/swiper.min.css">
    <link rel="stylesheet" href="/public/mobile/css/main.css">
    <script src="/public/mobile/js/rem.js"></script>
</head>
<body>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide part1">
            <a href="javascript:;"><img src="/public/mobile/images/wzlogo.png" class="logo" alt="多肉盒子"></a>
            <!--<div class="des">
                <p>玩转盒子：玩得起 赚的快</p>
                <p>游戏我发行，快乐伴你行</p>
            </div>-->
            <div class="img_box">
                <span class="s1"></span>
                <span class="s2"></span>
            </div>
            <div class="next"></div>
            <div class="btn" id="btn">
                <a href="javascript:;" class="ios" title="立即下载多肉盒子ios版app"></a>
            </div>
        </div>
    </div>
</div>

<script src="/public/mobile/js/jquery.min.js"></script>
<script src="/public/mobile/js/swiper.min.js"></script>
<script src="/public/mobile/js/index.js"></script>
</body>
</html>
