<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-积分记录</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/user/userbp.css?v=20191527" rel="stylesheet" />
</head>
<body>
    <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">

                <div class="layui-inline">
                    <button type="button" class="layui-btn layui-btn-normal">
                        <a href="addindex" class="layui_a"><i class="layui-icon layui-icon-add-circle-fine"></i><span class="layui_a_span">批量删除</span></a>
                    </button>
                </div>
            </div>
    </div>
    <div class="layui-form layui-border-box layui-table-view">
        <div class="layui-table-box">
            <div class="layui-table-header">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <thead>
                    <tr>
                        <th data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                        <th data-field="account" class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>用户名称</span></div></th>
                        <th data-field="account" class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>加减积分</span></div></th>
                        <th data-field="account" class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>操作类型</span></div></th>
                        <th data-field="account" class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>操作时间</span></div></th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="layui-table-body layui-table-main">
                <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                    <tbody id="list_body">
                    <?php foreach ($page as $key=>$value): ?>
                    <tr>
                        <td data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                        <td data-field="account" class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=get_zs_user_name($value['user'])?></span></div></td>
                        <td data-field="account" class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value['bp']?></span></div></td>
                        <td data-field="account" class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['bp_type']?></span></div></td>
                        <td data-field="account" class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$value['optime']?></span></div></td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <?=$showstr?>
    <script src="/public/js/jquery.js"></script>
    <script src="/public/layui/layui.all.js"></script>
    <script>
        let del = (tag)=>{
            let id = $(tag).data('id');
            $.get("/index/newsdel",{id:id},(msg)=>{
                if(msg.msg == 'ok'){
                    window.location.href = "/set/delindex";
                }else{
                    layer.msg('删除失败', {icon: 5});
                }
            },"json");
        }
    </script>
</body>
</html>
