<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-救助站列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/user/verify.css?=20181216" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th data-field="u_id" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span>经营性</span></div></th>
                    <th data-field="t_id" class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>姓名</span></div></th>
                    <td data-field="click" class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>手机号</span></div></td>
                    <th data-field="create_time" class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>所在地</span></div></th>
                    <th data-field="lbs" class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>时间</span></div></th>
                    <th data-field="register_ip" class="layui-unselect laytable-cell-1-0-6 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($arrData as $key=>$value): ?>
                    <tr>
                        <td data-field="id" class="layui-unselect laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value->id?></span></div></td>
                        <td data-field="u_id" class="layui-unselect laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=$value->commercial?></span></div></td>
                        <td data-field="t_id" class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=$value->real_name?></span></div></td>
                        <td data-field="content" class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value->mobile_num?></span></div></td>
                        <td data-field="click" class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$value->address?></span></div></td>
                        <td data-field="user_level" class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$value->create_time)?></span></div></td>
                        <td data-field="register_ip" class="layui-unselect laytable-cell-1-0-6"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-info" onclick="window.location.href='/user/verifydetail2?id=<?=$value->id?>'">查看</span></div></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
