<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-添加分类</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/card/addclassify.css" rel="stylesheet" />
</head>
<body>
<form class="layui-form" action="/card/classifyedit" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id" value="<?=$arrData->id?>">
    <div class="layui-card-header">话题分类修改</div>
    <div class="layui_body">
        <div class="layui-form-item">
            <label class="layui-form-label">分类名称</label>
            <div class="layui-input-inline">
                <input type="text" name="title" placeholder="请输入分类名称" autocomplete="off" class="layui-input" value="<?=$arrData->title?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">说明</label>
            <div class="layui-input-inline">
                <input type="text" name="info" placeholder="请输入分类说明" autocomplete="off" class="layui-input" value="<?=$arrData->info?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">分类图片</label>
            <div class="layui-input-inline">
                <input type="file" accept="image/*" name="pic" class="layui-input layui-pic">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="submit" class="layui-btn" value="立即提交">
            </div>
        </div>
    </div>
</form>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
</body>
</html>
