<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宠爱之家APP后台管理-帖子列表</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <link href="/public/css/common/public.css" rel="stylesheet" />
    <link href="/public/css/card/index.css?=201812127" rel="stylesheet" />
</head>
<body>
<div class="layui-form layui-card-header layuiadmin-card-header-auto">
    <form action="/user/usersearch" method="get">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题文档</label>
                <div class="layui-input-block">
                    <input type="text" name="search" placeholder="请输入标题文档" id="search_val" autocomplete="off" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <button type="submit" class="layui-btn layuiadmin-btn-useradmin">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="layui-form layui-border-box layui-table-view">
    <div class="layui-table-box">
        <div class="layui-table-header">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <thead>
                <tr>
                    <th class="laytable-cell-1-0-0"><div class="layui-table-cell"><span>ID</span></div></th>
                    <th class="laytable-cell-1-0-1"><div class="layui-table-cell"><span>创建者</span></div></th>
                    <th class="laytable-cell-1-0-2"><div class="layui-table-cell"><span>分类</span></div></th>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span>帖子内容</span></div></td>
                    <th class="laytable-cell-1-0-4"><div class="layui-table-cell"><span>点赞量</span></div></th>
                    <th class="laytable-cell-1-0-5"><div class="layui-table-cell"><span>时间</span></div></th>
                    <th class="laytable-cell-1-0-6"><div class="layui-table-cell"><span>定位</span></div></th>
                    <th class="laytable-cell-1-0-7 layui_th_end"><div class="layui-table-cell"><span>操作</span></div></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="layui-table-body layui-table-main">
            <table cellspacing="0" cellpadding="0" border="0" class="layui-table">
                <tbody id="list_body">
                <?php foreach ($page as $key=>$value): ?>
                <tr>
                    <td class="laytable-cell-1-0-0"><div class="layui-table-cell"><span><?=$value['id']?></span></div></td>
                    <td class="laytable-cell-1-0-1"><div class="layui-table-cell"><span><?=get_zs_user_name($value['u_id'])?></span></div></td>
                    <td class="laytable-cell-1-0-2"><div class="layui-table-cell"><span><?=get_zs_type_name($value['t_id'])?></span></div></td>
                    <td class="laytable-cell-1-0-3"><div class="layui-table-cell"><span><?=$value['content']?></span></div></td>
                    <td class="laytable-cell-1-0-4"><div class="layui-table-cell"><span><?=$value['click']?></span></div></td>
                    <td class="laytable-cell-1-0-5"><div class="layui-table-cell"><span><?=date("Y-m-d H:i:s",$value['create_time'])?></span></div></td>
                    <td class="laytable-cell-1-0-6"><div class="layui-table-cell"><span><?=$value['lbs']?></span></div></td>
                    <td class="laytable-cell-1-0-7"><div class="layui-table-cell"><span class="layui-btn layui-btn-xs layui-btn-danger" data-id="<?=$value['id']?>" onclick="del(this)">删除</span></div></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?=$showstr?>
<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script>
    let del = (tag)=>{
        let id = $(tag).data('id');
        $.get("/card/del",{id:id},(msg)=>{
            if(msg.msg == 'ok'){
                window.location.href = "/card/index";
            }else{
                layer.msg('删除失败', {icon: 5});
            }
        },"json");
    }
</script>
</body>
</html>
