<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="关于宠爱，宠爱简介，宠爱资料">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/public/css/media/public.css">
    <link rel="stylesheet" href="/public/css/media/base.css">
    <link rel="stylesheet" href="/public/css/media/about/index.css">
</head>
<body>
    <div class="header about-top news-top">
        <?php load_view("inc/header");?>
    </div>
    <!-- about -->
    <div style="text-align: center;">
        <img src="/public/img/media/common/lct.jpg" height="4112" width="800" alt="">
    </div>

    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/media.js"></script>
</body>
</html>
