<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱宠物救助站入驻登录，宠爱宠物救助站合作登录，宠物救助站信息登录">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/public/css/media/public.css">
    <link rel="stylesheet" href="/public/css/media/base.css">
    <link rel="stylesheet" href="/public/css/media/rescueinfo/login.css">
</head>
<body>
<div class="header">
    <!--  header  -->
    <div class="nav-bar">
        <div class="main">
            <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
            <ul class="nav">
                <!--<li class=""><a href="../index.html">首页</a></li>
                <li class="head-about"><a href="../news.html">宠爱动态</a></li>
                <li class="head-about cur"><a href="../rescue.html">宠爱救助站</a></li>
                <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>-->
                <li class="head-about"><a href="javascript:void(0);">加入宠爱之家官方救助平台</a></li>
                <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
            </ul>
        </div>
    </div>
</div>
<!--  banner  -->
<div class="banner">
    <img src="/public/img/media/rescueinfo/banner.png" width="100%" alt="">
</div>
<!--  footer  -->
<div class="footer">
    <div class="center">
        <p><a href="javascript:void(0);">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved</a></p>
    </div>
</div>
<!--  popup  -->
<div class="popup">
    <h4>动态登录</h4>
    <div class="input-box"><input class="input-text" id="number" type="number" placeholder="手机号码" max="11"></div>
    <div class="input-box code-box clearfix"><input id="code" class="input-text code fl" type="number" placeholder="验证码" max="6"><input class="input-text code-btn fl" type="button" onclick="time()" value="获取验证码(60)"></div>
    <div class="input-box"><input class="login-btn" type="button" value="立即登录" onclick="send()" ></div>
</div>

<script src="/public/js/jquery.js"></script>
<script>
    //倒计时
    function time() {
        let len = $("#number").val().length;
        if(len == 11){
            $(".code-btn").addClass("on");
            var time = 59;
            $(".code-btn").attr("disabled", true);
            var timer = setInterval(function() {
                if (time == 0) {
                    clearInterval(timer);
                    $(".code-btn").attr("disabled", false);
                    $(".code-btn").val("再次获取");
                    $(".code-btn").removeClass("on");
                } else {
                    $('.code-btn').val("获取验证码(" + time + ")");
                    time--;
                }
            }, 1000);
            $.post("/index/sendvcode",{mobile_num:$("#number").val()},function (msg) {},"json");
        }else{
            alert("请先输入手机号");
        }
    }
    //登录
    function send() {
        let phone = $("#number").val();
        let dynamic_code = $("#code").val();
        $.post("/index/ajaxsms",{phone:phone,dynamic_code:dynamic_code},function (msg) {
            if(msg.code == 0){
                window.location.href = "/index/ajaxmobilenum";
            }else{
                alert(msg.message);
            }
        },"json");
    }
</script>
</body>
</html>
