<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱资讯，宠爱新闻，宠爱动态">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/public/css/media/public.css">
    <link rel="stylesheet" href="/public/css/media/base.css">
    <link rel="stylesheet" href="/public/css/media/news/index.css">
    <link href="/public/layui/css/layui.css" rel="stylesheet" media="all" />
    <style>#pages{margin: 10px 10px;line-height: 34px;}#pages a:nth-last-of-type(1){margin-right: 10px;}</style>
</head>
<body>
    <div class="header about-top news-top">
        <?php load_view("inc/header");?>
    </div>
    <!--  news list  -->
    <div class="news-list center">
        <div class="tit">宠爱动态</div>
        <ul class="news-item">
            <?php foreach ($page as $key=>$value): ?>
            <li>
                <span class="pic"><img src="http://<?=server('SERVER_NAME')?>/public/upload/<?=json_decode($value['pic'],true)[0]?>"></span>
                <div class="item-pos">
                    <span class="date"><?=date("Y/m/d",$value['create_time'])?></span>
                    <p class="title"><?=$value['title']?></p>
                    <p class="des"><?=$value['content']?></p>
                    <a href="/index/detail?type=news&id=<?=$value['id']?>">查看详情</a>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
        <?=$showstr?>
    </div>

    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/media.js"></script>
    <script src="/public/layui/layui.all.js"></script>

</body>
</html>
