<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱宠物救助站，宠爱宠物救助，宠物救助站">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/public/css/media/public.css">
    <link rel="stylesheet" href="/public/css/media/base.css">
    <link rel="stylesheet" href="/public/css/media/rescue/index.css">
</head>
<body>
    <div class="header about-top news-top">
        <?php load_view("inc/header");?>
    </div>
    <!--  救助站  -->
    <div class="rescue-box center">
        <div class="clearfix nav-box"><div class="tit fl">申请加入宠爱平台流程</div><a class="join-btn fl" href="/index/guide" target="_blank">查看流程图</a><a class="join-btn fl" href="/index/login" target="_blank">申请加入</a></div>
        <ul class="news-item">
            <li>
                <span class="pic"><img src="/public/img/media/rescue/flow1.png"></span>
                <p class="pos">1、注册登录</p>
            </li>
            <li>
                <span class="pic"><img src="/public/img/media/rescue/flow2.png"></span>
                <p class="pos">2、实名认证</p>
            </li>
            <li>
                <span class="pic"><img src="/public/img/media/rescue/flow3.png"></span>
                <p class="pos">3、提交信息</p>
            </li>
            <li>
                <span class="pic"><img src="/public/img/media/rescue/flow4.png"></span>
                <p class="pos">4、等待审核</p>
            </li>
        </ul>
       <!-- <div class="tit join">点击加入宠爱平台</div>-->
    </div>

    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/media.js"></script>
</body>
</html>
