<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>宠爱之家APP后台管理-登录</title>
    <link href="/public/layui/css/layui.css" rel="stylesheet" />
    <link href="/public/css/login/login.css" rel="stylesheet" />
</head>
<body onkeydown="keyLogin();">
<div class="layadmin-user-login layadmin-user-display-show" id="LAY-user-login">
    <div class="layadmin-user-login-main">
        <div class="layadmin-user-login-box layadmin-user-login-header">
            <h2>宠爱之家-APP后台管理系统</h2>
        </div>
        <div class="layadmin-user-login-box layadmin-user-login-body layui-form">
            <div class="layui-form-item">
                <label class="layadmin-user-login-icon layui-icon layui-icon-username" for="LAY-user-login-username"></label>
                <input type="text" name="username" id="LAY-user-login-username" lay-verify="required" placeholder="用户名" class="layui-input">
            </div>
            <div class="layui-form-item">
                <label class="layadmin-user-login-icon layui-icon layui-icon-password" for="LAY-user-login-password"></label>
                <input type="password" name="password" id="LAY-user-login-password" lay-verify="required" placeholder="密码" class="layui-input">
            </div>
            <div class="layui-form-item">
                <div class="layui-row">
                    <div class="layui-col-xs7">
                        <label class="layadmin-user-login-icon layui-icon layui-icon-vercode" for="LAY-user-login-vercode"></label>
                        <input type="text" name="vercode" id="LAY-user-login-vercode" lay-verify="required" placeholder="图形验证码" class="layui-input">
                    </div>
                    <div class="layui-col-xs5">
                        <div style="margin-left: 10px;">
                            <img src="/login/code" onclick="this.src='/login/code?data='+Math.random()" class="layadmin-user-login-codeimg" id="LAY-user-get-vercode" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <button id="btn" class="layui-btn layui-btn-fluid" lay-submit lay-filter="LAY-user-login-submit">登 入</button>
            </div>
        </div>
    </div>

    <div class="layui-trans layadmin-user-login-footer">

        <p>© 2018 <a href="http://www.zhishengwh.com/" target="_blank">zhishengwh.com</a></p>
        <p>
            <span><a href="http://www.zhishengwh.com/" target="_blank">前往官网</a></span>
        </p>
    </div>

    <!--<div class="ladmin-user-login-theme">
      <script type="text/html" template>
        <ul>
          <li data-theme=""><img src="{{ layui.setter.base }}style/res/bg-none.jpg"></li>
          <li data-theme="#03152A" style="background-color: #03152A;"></li>
          <li data-theme="#2E241B" style="background-color: #2E241B;"></li>
          <li data-theme="#50314F" style="background-color: #50314F;"></li>
          <li data-theme="#344058" style="background-color: #344058;"></li>
          <li data-theme="#20222A" style="background-color: #20222A;"></li>
        </ul>
      </script>
    </div>-->
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/layui/layui.all.js"></script>
<script src="/public/js/js_cookie.js"></script>
<script>
    let postadmin = (user,pass) =>{
        $.post('/login/login',{u:user,p:pass},(msg)=>{
            msg.msg == 'ok' ? window.location.href='/admin/index' : layer.msg('账号密码错误', {icon:5})
        },"json");
    };
    $(function () {
        $("#btn").on("click",function () {
            let vercodeVal = $("#LAY-user-login-vercode").val().toLowerCase();
            let cookieVal = getCookie("yzm");
            let username = $('#LAY-user-login-username').val();
            let password = $('#LAY-user-login-password').val();
            vercodeVal == cookieVal ? postadmin(username,password) : layer.msg("验证码失败", {icon: 5});
        });
    });
    function keyLogin(){
        if (event.keyCode==13)  //回车键的键值为13
            document.getElementById("btn").click();
    }

</script>
</body>
</html>
