<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>宠爱之家-wap联系我们</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/pages/css/profile.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/apps/css/ticket.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/layouts/layout4/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
<!--  公共头部  -->
<?php $this->view->partial("inc/header")?>
<div class="clearfix"> </div>
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!--  公共左部  -->
        <?php $this->view->partial("inc/left")?>
    </div>
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-head">
                <div class="page-title">
                    <h1>wap联系我们</h1>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <a href="/index">主页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span class="active">二级</span>
                </li>
            </ul>
            <div class="profile-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light bordered">
                            <div class="portlet-body">
                                <div class="tab-content">
                                    <div class="tab-pane active">
                                        <form role="form" action="/news/wapcontactus/news/2" method="post" enctype="multipart/form-data">
                                            <div class="form-group">
                                                <label class="control-label">主标题</label>
                                                <input type="text" name="title" placeholder="" class="form-control" value="<?=$result->title?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">地址：</label>
                                                <input type="text" name="address" placeholder="" class="form-control" value="<?=$result->address?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">邮编：</label>
                                                <input type="text" name="postal_code"  placeholder="" class="form-control" value="<?=$result->postal_code?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">客服QQ：</label>
                                                <input type="number" name="qq"  placeholder="" class="form-control" value="<?=$result->qq?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">电子邮箱：</label>
                                                <input type="email" name="email"  placeholder="" class="form-control" value="<?=$result->email?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">二维码标题1</label>
                                                <input type="text" name="code_title1"  placeholder="" class="form-control" value="<?=$result->code_title1?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">二维码图片1</label>
                                                <div style="overflow: hidden;">
                                                    <div class="col-md-2" style="padding-left: 0;float: initial;display: inline-block;">
                                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                                <img src="<?=$result->code_pic1?>" />
                                                            </div>
                                                            <div>
                                                                <span class="btn red btn-outline btn-file">
                                                                <span class="fileinput-new">选择图片</span>
                                                                <span class="fileinput-exists">更换图片</span>
                                                                <input type="file" name="code_pic1"> </span>
                                                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">删除</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">二维码标题2</label>
                                                <input type="text" name="code_title2"  placeholder="" class="form-control" value="<?=$result->code_title2?>">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">二维码图片2</label>
                                                <div style="overflow: hidden;">
                                                    <div class="col-md-2" style="padding-left: 0;float: initial;display: inline-block;">
                                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                                <img src="<?=$result->code_pic2?>" />
                                                            </div>
                                                            <div>
                                                                <span class="btn red btn-outline btn-file">
                                                                <span class="fileinput-new">选择图片</span>
                                                                <span class="fileinput-exists">更换图片</span>
                                                                <input type="file" name="code_pic2"> </span>
                                                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">删除</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="margiv-top-10">
                                                <button type="submit" class="btn green">提交</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="/assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/profile.min.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
<script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.4.6&key=2e44013a0fd023709eb2d23ccf7053c6"></script>
<script>
    var geocoder = new AMap.Geocoder({
        // city 指定进行编码查询的城市，支持传入城市名、adcode 和 citycode
        city: '全国'
    });
    var address = '北京市海淀区苏州街';//这里是需要转化的地址

    geocoder.getLocation(address, function(status, result) {
        if (status === 'complete' && result.info === 'OK') {
            // result为对应的地理位置详细信息
        }
    };
</script>
</body>
</html>
